from core import *

CO = "Sweep Inc."
ADDR = "3980 Blvd St-Elzear O, Laval (Québec) H7P 0M2, Canada"
M = f'<a href="mailto:{EMAIL}">{EMAIL}</a>'

PRIVACY = T(f"""
<h2>Who we are</h2><p>Sweep is operated by <strong>{CO}</strong>, {ADDR} (“Sweep”, “we”). This policy covers the website makeitsweep.com and the app at app.makeitsweep.com. It explains what personal information we collect, why, how long we keep it and the rights you have. It is written to meet Quebec’s <em>Act respecting the protection of personal information in the private sector</em> (Law 25) and Canada’s PIPEDA.</p>
<h2>Person in charge of personal information</h2><p>The President of {CO} is responsible for the protection of personal information at Sweep. Contact: {M}.</p>
<h2>What we collect</h2><ul>
<li><strong>Account:</strong> your username, email address (also used for password reset), password (stored only as a secure hash, never readable), your language, and the date and time you accepted the Terms of use and this policy.</li>
<li><strong>What you enter:</strong> trading accounts, trades, journals, payouts, expenses, settings, and the screenshots you upload.</li>
<li><strong>Technical:</strong> IP addresses, kept for up to 24 hours and only to limit log-in, sign-up and password-reset attempts.</li>
<li><strong>On your device:</strong> a session cookie (<code>tj_session</code>, lasting 30 days, HttpOnly, Secure) that keeps you signed in, and interface preferences in your browser’s local storage (theme, language, filters, last account used). The website stores your language choice.</li>
<li><strong>Campaign link:</strong> if you arrive from one of our campaign links, the website stores a <code>sweep_utm</code> cookie for 30 days with that link’s campaign tags (source, medium, campaign and content). Only the first link is kept. The app reads it when you create an account, to record which campaign brought you. It contains no other information and is not shared with anyone.</li></ul>
<p>We do not use analytics or advertising cookies, and no third-party trackers, on the website or in the app.</p>
<h2>Why we use it</h2><p>To create and secure your account, store and show your data, calculate your statistics, send password-reset emails, answer your requests, prevent abuse, and meet our legal obligations. We use only what we need for these purposes, and we do not use your information for advertising or profiling.</p>
<h2>What we never do</h2><p>We do not sell your personal information. We do not share your trading data with prop firms, brokers, advertisers or anyone else. The administrator page shows usernames and usage only, never your trades or notes.</p>
<h2>Where your data is stored</h2><p>Your data is stored on Sweep’s server, hosted by HostArmada. The database sits outside the public web folder. Our hosting provider’s servers may be located outside Quebec; before your information is stored or processed outside Quebec, we assess that it will receive adequate protection, as the law requires.</p>
<h2>Service providers and third parties</h2><ul>
<li><strong>Hosting:</strong> HostArmada stores the website, the app and its database.</li>
<li><strong>Fonts in the app:</strong> the app loads the Geist typeface from Google Fonts. When it does, your browser connects to Google, which can see your IP address. The website hosts its fonts itself.</li>
<li><strong>Email:</strong> password-reset emails are sent from Sweep’s own server.</li>
<li><strong>Discord:</strong> only if you connect your Discord account. See below.</li>
<li><strong>Stripe (payments):</strong> handles your payment details when you subscribe. See “Payments” below.</li>
<li><strong>Google (Gemini API, Google Search):</strong> when you use an AI feature, and to prepare economic calendar reports. See “Sweep AI” below.</li></ul>
<h2>Sweep AI</h2><p>Sweep AI is optional. Nothing is sent to the AI provider until you tap an AI action (marked ✦) or send a message to Ask Sweep. Then Sweep sends only what that action needs to Google’s Gemini API, for example the text you typed, the screenshot or receipt you chose, the details of the trade being reviewed, or short summaries of your own statistics. Results are shown as drafts you check before anything is saved. To avoid repeating identical requests, AI results are kept on Sweep’s server for up to 30 days, together with a usage log (action type and date) used to apply the daily limit. Deleting your account also deletes its AI history.</p>
<ul><li><strong>Ask Sweep:</strong> when you send a message, Sweep sends your message, the last few messages of the conversation, and short summaries of your own statistics (for example totals and breakdowns by session or setup) to Google’s Gemini API to write the answer. The conversation is kept only in your browser for the current session.</li>
<li><strong>Economic calendar and market reports:</strong> Sweep uses Google’s Gemini API with Google Search to look up public economic figures and market news. These requests contain no personal data. Reports are shared with all Sweep users.</li></ul>
<p>Settings → Sweep AI in the app explains exactly what is sent. AI output can be wrong and is not financial advice.</p>
<h2>Payments</h2><p>Paid plans are processed by Stripe. Sweep never receives or stores full card numbers. Sweep stores your Stripe customer ID, your plan, your subscription status and dates, and which upgrade screen led to a subscription (used only for internal statistics). Sweep also stores AI usage counts per day and per month to apply plan limits. Deleting your Sweep account cancels any active subscription and removes billing records from Sweep; Stripe keeps its own payment records as required by law.</p>
<h2>Social features, Discord, referrals and feedback</h2><ul>
<li><strong>Social features are off by default.</strong> If you join a league, a crew or a buddy, other members see your username, rank and consistency; a buddy also sees your rings and streak; crew members see the crew’s activity feed and reactions. Never your P&amp;L, amounts, trades or accounts. You can leave at any time.</li>
<li><strong>Game data:</strong> Sweep stores your XP, level, rank, badges, missions, bosses, streaks, chests and season progress to run these features.</li>
<li><strong>Discord:</strong> if you connect Discord, Sweep stores your Discord user ID and username and shares your Sweep rank with Discord to assign a role on the servers that use it. Disconnecting stops this.</li>
<li><strong>Referrals:</strong> Sweep records who invited whom and whether the qualifying activity (10 trades on 3 different days, or a paid plan) was reached, to grant the rewards.</li>
<li><strong>Feedback:</strong> ideas and bug reports you send from the app, with their status, are stored so we can follow up and tell you when it ships.</li></ul>
<h2>Charts</h2><p>Charts display CME market data, which contains no personal information.</p>
<h2>Share cards</h2><p>Share cards are generated on your device. Nothing is uploaded unless you share the image yourself.</p>
<h2>How long we keep it</h2><p>We keep your information while your account is open. If you delete your account in Settings, your account and all its data, screenshots included, are deleted immediately. IP addresses are kept for up to 24 hours.</p>
<h2>Your rights</h2><p>You can access, correct or delete your personal information, withdraw your consent, and receive your data in a structured, commonly used format:</p><ul>
<li><strong>Export:</strong> one click gives you a ZIP file with a re-importable backup, CSV spreadsheets (trades, accounts, payouts, expenses, journal) and all your screenshots.</li>
<li><strong>Delete:</strong> Settings → Delete my account (your password is required), or ask us by email.</li>
<li><strong>Anything else:</strong> write to {M}. We answer within 30 days.</li></ul>
<p>You can also file a complaint with the Commission d’accès à l’information du Québec.</p>
<h2>Security</h2><p>Sweep uses HTTPS only, strict security headers, hashed passwords, one-time password-reset links valid for one hour, limits on sign-in attempts and anti-bot checks. If a confidentiality incident presents a risk of serious injury, we will notify you and the Commission d’accès à l’information as required by law.</p>
<h2>Age</h2><p>Sweep is for people 18 and older. You must confirm you are 18 or older to create an account.</p>
<h2>Changes</h2><p>We will post changes to this policy on this page with a new effective date, and announce significant changes in the app.</p>
""", f"""
<h2>Qui sommes-nous</h2><p>Sweep est exploité par <strong>{CO}</strong>, {ADDR} (« Sweep », « nous »). La présente politique couvre le site makeitsweep.com et l’application app.makeitsweep.com. Elle explique quels renseignements personnels nous recueillons, pourquoi, combien de temps nous les gardons et quels sont tes droits. Elle est rédigée pour respecter la <em>Loi sur la protection des renseignements personnels dans le secteur privé</em> du Québec (Loi 25) et la LPRPDE.</p>
<h2>Responsable de la protection des renseignements personnels</h2><p>Le président de {CO} est responsable de la protection des renseignements personnels chez Sweep. Contact : {M}.</p>
<h2>Ce que nous recueillons</h2><ul>
<li><strong>Compte :</strong> ton nom d’utilisateur, ton adresse courriel (servant aussi à la réinitialisation du mot de passe), ton mot de passe (conservé uniquement sous forme de hachage sécurisé, jamais lisible), ta langue, et la date et l’heure où tu as accepté les Conditions d’utilisation et la présente politique.</li>
<li><strong>Ce que tu saisis :</strong> comptes de trading, trades, journaux, payouts, dépenses, réglages et captures d’écran que tu téléverses.</li>
<li><strong>Renseignements techniques :</strong> adresses IP, conservées jusqu’à 24 heures et uniquement pour limiter les tentatives de connexion, d’inscription et de réinitialisation.</li>
<li><strong>Sur ton appareil :</strong> un témoin de session (<code>tj_session</code>, 30 jours, HttpOnly, Secure) qui te garde connecté, et tes préférences dans le stockage local du navigateur (thème, langue, filtres, dernier compte). Le site conserve ton choix de langue.</li>
<li><strong>Lien de campagne :</strong> si tu arrives par un de nos liens de campagne, le site conserve un témoin <code>sweep_utm</code> pendant 30 jours avec les étiquettes de campagne de ce lien (source, support, campagne et contenu). Seul le premier lien est gardé. L’application le lit quand tu crées un compte, pour noter quelle campagne t’a amené. Il ne contient aucun autre renseignement et n’est partagé avec personne.</li></ul>
<p>Nous n’utilisons aucun témoin d’analytique ou de publicité, ni aucun traqueur tiers, ni sur le site ni dans l’application.</p>
<h2>Pourquoi nous les utilisons</h2><p>Pour créer et sécuriser ton compte, conserver et afficher tes données, calculer tes statistiques, envoyer les courriels de réinitialisation, répondre à tes demandes, prévenir les abus et respecter nos obligations légales. Nous n’utilisons que ce qui est nécessaire à ces fins, et jamais à des fins publicitaires ou de profilage.</p>
<h2>Ce que nous ne faisons jamais</h2><p>Nous ne vendons pas tes renseignements personnels. Nous ne partageons pas tes données de trading avec des prop firms, courtiers, annonceurs ou qui que ce soit. La page d’administration ne montre que les noms d’utilisateur et l’utilisation, jamais tes trades ni tes notes.</p>
<h2>Où tes données sont conservées</h2><p>Tes données sont conservées sur le serveur de Sweep, hébergé par HostArmada. La base de données est hors du dossier web public. Les serveurs de notre hébergeur peuvent être situés hors du Québec; avant que tes renseignements soient conservés ou traités hors du Québec, nous évaluons qu’ils bénéficieront d’une protection adéquate, comme l’exige la loi.</p>
<h2>Fournisseurs et tiers</h2><ul>
<li><strong>Hébergement :</strong> HostArmada héberge le site, l’application et sa base de données.</li>
<li><strong>Polices dans l’application :</strong> l’application charge la police Geist depuis Google Fonts. Ton navigateur se connecte alors à Google, qui peut voir ton adresse IP. Le site héberge lui-même ses polices.</li>
<li><strong>Courriel :</strong> les courriels de réinitialisation sont envoyés depuis le serveur de Sweep.</li>
<li><strong>Discord :</strong> seulement si tu connectes ton compte Discord. Voir plus bas.</li>
<li><strong>Stripe (paiements) :</strong> traite tes données de paiement quand tu t’abonnes. Voir « Paiements » ci-dessous.</li>
<li><strong>Google (API Gemini, Recherche Google) :</strong> quand tu utilises une fonction IA, et pour préparer les rapports du calendrier économique. Voir « Sweep AI » ci-dessous.</li></ul>
<h2>Sweep AI</h2><p>Sweep AI est optionnel. Rien n’est envoyé au fournisseur d’IA tant que tu ne touches pas une action IA (marquée ✦) ou n’envoies pas de message à Ask Sweep. Sweep transmet alors à l’API Gemini de Google seulement ce dont l’action a besoin, par exemple le texte que tu as écrit, la capture ou le reçu choisi, les détails du trade révisé, ou de courts résumés de tes propres statistiques. Les résultats sont présentés comme des brouillons que tu vérifies avant tout enregistrement. Pour éviter de répéter des demandes identiques, les résultats de l’IA sont conservés sur le serveur de Sweep jusqu’à 30 jours, avec un journal d’utilisation (type d’action et date) servant à appliquer la limite quotidienne. Supprimer ton compte supprime aussi son historique IA.</p>
<ul><li><strong>Ask Sweep :</strong> quand tu envoies un message, Sweep transmet ton message, les derniers messages de la conversation et de courts résumés de tes propres statistiques (par exemple les totaux et les répartitions par session ou setup) à l’API Gemini de Google pour rédiger la réponse. La conversation est conservée seulement dans ton navigateur, pour la session en cours.</li>
<li><strong>Calendrier économique et rapports de marché :</strong> Sweep utilise l’API Gemini de Google avec la Recherche Google pour trouver des chiffres économiques et des nouvelles de marché publics. Ces requêtes ne contiennent aucune donnée personnelle. Les rapports sont partagés avec tous les utilisateurs de Sweep.</li></ul>
<p>Réglages → Sweep AI dans l’app explique exactement ce qui est transmis. Les réponses de l’IA peuvent être erronées et ne sont pas des conseils financiers.</p>
<h2>Paiements</h2><p>Les forfaits payants sont traités par Stripe. Sweep ne reçoit ni ne conserve jamais les numéros de carte complets. Sweep conserve ton identifiant client Stripe, ton forfait, le statut et les dates de ton abonnement, et l’écran de mise à niveau qui a mené à l’abonnement (servant uniquement à des statistiques internes). Sweep conserve aussi le nombre d’utilisations de l’IA par jour et par mois pour appliquer les limites du forfait. Supprimer ton compte Sweep annule tout abonnement actif et supprime les données de facturation chez Sweep; Stripe conserve ses propres registres de paiement, comme l’exige la loi.</p>
<h2>Fonctions sociales, Discord, parrainage et feedback</h2><ul>
<li><strong>Les fonctions sociales sont désactivées par défaut.</strong> Si tu rejoins une ligue, un crew ou un buddy, les autres membres voient ton pseudo, ton rang et ta régularité; un buddy voit aussi tes anneaux et ton streak; les membres d’un crew voient son fil d’activité et ses réactions. Jamais ton P&amp;L, tes montants, tes trades ou tes comptes. Tu peux te retirer en tout temps.</li>
<li><strong>Données de jeu :</strong> Sweep conserve ton XP, ton niveau, ton rang, tes badges, missions, boss, streaks, coffres et ta progression de saison pour faire fonctionner ces fonctions.</li>
<li><strong>Discord :</strong> si tu connectes Discord, Sweep conserve ton identifiant et ton nom d’utilisateur Discord et transmet ton rang Sweep à Discord pour attribuer un rôle sur les serveurs qui l’utilisent. Te déconnecter arrête ce partage.</li>
<li><strong>Parrainage :</strong> Sweep enregistre qui a invité qui et si l’activité requise (10 trades sur 3 jours différents, ou un forfait payant) est atteinte, pour accorder les récompenses.</li>
<li><strong>Feedback :</strong> les idées et signalements de bugs que tu envoies depuis l’app, avec leur statut, sont conservés pour qu’on puisse y donner suite et te dire quand c’est livré.</li></ul>
<h2>Graphiques</h2><p>Les graphiques affichent des données de marché du CME, qui ne contiennent aucun renseignement personnel.</p>
<h2>Cartes à partager</h2><p>Les cartes à partager sont créées sur ton appareil. Rien n’est téléversé, sauf si tu partages toi-même l’image.</p>
<h2>Durée de conservation</h2><p>Nous conservons tes renseignements tant que ton compte est ouvert. Si tu supprimes ton compte dans les réglages, ton compte et toutes ses données, captures comprises, sont supprimés immédiatement. Les adresses IP sont conservées jusqu’à 24 heures.</p>
<h2>Tes droits</h2><p>Tu peux accéder à tes renseignements personnels, les faire rectifier ou supprimer, retirer ton consentement et obtenir tes données dans un format technologique structuré et couramment utilisé :</p><ul>
<li><strong>Exporter :</strong> un clic te donne un fichier ZIP avec une sauvegarde réimportable, des tableurs CSV (trades, comptes, payouts, dépenses, journal) et toutes tes captures.</li>
<li><strong>Supprimer :</strong> Réglages → Supprimer mon compte (mot de passe requis), ou demande-le-nous par courriel.</li>
<li><strong>Toute autre demande :</strong> écris à {M}. Nous répondons dans un délai de 30 jours.</li></ul>
<p>Tu peux aussi porter plainte auprès de la Commission d’accès à l’information du Québec.</p>
<h2>Sécurité</h2><p>Sweep utilise uniquement HTTPS, des en-têtes de sécurité stricts, des mots de passe hachés, des liens de réinitialisation à usage unique valides une heure, des limites de tentatives de connexion et une protection anti-robots. Si un incident de confidentialité présente un risque de préjudice sérieux, nous t’en aviserons, ainsi que la Commission d’accès à l’information, comme l’exige la loi.</p>
<h2>Âge</h2><p>Sweep s’adresse aux personnes de 18 ans et plus. Tu dois confirmer avoir 18 ans ou plus pour créer un compte.</p>
<h2>Modifications</h2><p>Nous publierons toute modification sur cette page avec une nouvelle date d’entrée en vigueur, et annoncerons les changements importants dans l’application.</p>
""", f"""
<h2>Quiénes somos</h2><p>Sweep es operado por <strong>{CO}</strong>, {ADDR} («Sweep», «nosotros»). Esta política cubre el sitio makeitsweep.com y la app en app.makeitsweep.com. Explica qué información personal recopilamos, para qué, cuánto tiempo la conservamos y qué derechos tienes. Está redactada para cumplir la ley de protección de la información personal en el sector privado de Quebec (Ley 25) y la ley canadiense PIPEDA.</p>
<h2>Responsable de la información personal</h2><p>El presidente de {CO} es responsable de la protección de la información personal en Sweep. Contacto: {M}.</p>
<h2>Qué recopilamos</h2><ul>
<li><strong>Cuenta:</strong> tu usuario, correo (también usado para restablecer la contraseña), contraseña (guardada solo como hash seguro, nunca legible), tu idioma, y la fecha y hora en que aceptaste los Términos de uso y esta política.</li>
<li><strong>Lo que introduces:</strong> cuentas de trading, operaciones, diarios, payouts, gastos, ajustes y las capturas que subes.</li>
<li><strong>Técnico:</strong> direcciones IP, guardadas hasta 24 horas y solo para limitar intentos de acceso, registro y restablecimiento.</li>
<li><strong>En tu dispositivo:</strong> una cookie de sesión (<code>tj_session</code>, 30 días, HttpOnly, Secure) que mantiene tu sesión, y preferencias en el almacenamiento local (tema, idioma, filtros, última cuenta). El sitio guarda tu idioma.</li>
<li><strong>Enlace de campaña:</strong> si llegas desde uno de nuestros enlaces de campaña, el sitio guarda una cookie <code>sweep_utm</code> durante 30 días con las etiquetas de campaña de ese enlace (fuente, medio, campaña y contenido). Solo se guarda el primer enlace. La app la lee al crear tu cuenta, para registrar qué campaña te trajo. No contiene ninguna otra información y no se comparte con nadie.</li></ul>
<p>No usamos cookies de analítica ni de publicidad, ni rastreadores de terceros, ni en el sitio ni en la app.</p>
<h2>Para qué la usamos</h2><p>Para crear y proteger tu cuenta, guardar y mostrar tus datos, calcular tus estadísticas, enviar correos de restablecimiento, responder a tus solicitudes, prevenir abusos y cumplir obligaciones legales. Solo usamos lo necesario y nunca para publicidad ni perfiles.</p>
<h2>Lo que nunca hacemos</h2><p>No vendemos tu información personal. No compartimos tus datos de trading con prop firms, brókers, anunciantes ni nadie. La página de administración muestra solo usuarios y uso, nunca tus operaciones ni notas.</p>
<h2>Dónde se guardan tus datos</h2><p>Tus datos se guardan en el servidor de Sweep, alojado por HostArmada. La base de datos está fuera de la carpeta web pública. Los servidores de nuestro proveedor pueden estar fuera de Quebec; antes de que tu información se guarde o procese fuera de Quebec, evaluamos que reciba una protección adecuada, como exige la ley.</p>
<h2>Proveedores y terceros</h2><ul>
<li><strong>Alojamiento:</strong> HostArmada aloja el sitio, la app y su base de datos.</li>
<li><strong>Fuentes en la app:</strong> la app carga la tipografía Geist desde Google Fonts. Tu navegador se conecta entonces a Google, que puede ver tu dirección IP. El sitio aloja sus propias fuentes.</li>
<li><strong>Correo:</strong> los correos de restablecimiento se envían desde el servidor de Sweep.</li>
<li><strong>Discord:</strong> solo si conectas tu cuenta de Discord. Ver más abajo.</li>
<li><strong>Stripe (pagos):</strong> procesa tus datos de pago cuando te suscribes. Ver «Pagos» más abajo.</li>
<li><strong>Google (API Gemini, Búsqueda de Google):</strong> cuando usas una función de IA, y para preparar los informes del calendario económico. Ver «Sweep AI» más abajo.</li></ul>
<h2>Sweep AI</h2><p>Sweep AI es opcional. No se envía nada al proveedor de IA hasta que tocas una acción de IA (marcada con ✦) o envías un mensaje a Ask Sweep. Entonces Sweep envía a la API Gemini de Google solo lo que esa acción necesita, por ejemplo el texto que escribiste, la captura o el recibo elegido, los detalles de la operación revisada o breves resúmenes de tus propias estadísticas. Los resultados se muestran como borradores que revisas antes de guardar nada. Para no repetir solicitudes idénticas, los resultados de la IA se guardan en el servidor de Sweep hasta 30 días, junto con un registro de uso (tipo de acción y fecha) para aplicar el límite diario. Eliminar tu cuenta también elimina su historial de IA.</p>
<ul><li><strong>Ask Sweep:</strong> cuando envías un mensaje, Sweep envía tu mensaje, los últimos mensajes de la conversación y breves resúmenes de tus propias estadísticas (por ejemplo totales y desgloses por sesión o setup) a la API Gemini de Google para redactar la respuesta. La conversación se guarda solo en tu navegador durante la sesión actual.</li>
<li><strong>Calendario económico e informes de mercado:</strong> Sweep usa la API Gemini de Google con la Búsqueda de Google para buscar cifras económicas y noticias de mercado públicas. Estas solicitudes no contienen datos personales. Los informes se comparten con todos los usuarios de Sweep.</li></ul>
<p>Ajustes → Sweep AI en la app explica exactamente qué se envía. Las respuestas de la IA pueden ser erróneas y no son asesoramiento financiero.</p>
<h2>Pagos</h2><p>Los planes de pago los procesa Stripe. Sweep nunca recibe ni guarda números de tarjeta completos. Sweep guarda tu ID de cliente de Stripe, tu plan, el estado y las fechas de tu suscripción, y qué pantalla de mejora llevó a la suscripción (solo para estadísticas internas). Sweep también guarda el número de usos de la IA por día y por mes para aplicar los límites del plan. Eliminar tu cuenta de Sweep cancela cualquier suscripción activa y borra los registros de facturación en Sweep; Stripe conserva sus propios registros de pago, como exige la ley.</p>
<h2>Funciones sociales, Discord, referidos y feedback</h2><ul>
<li><strong>Las funciones sociales están desactivadas por defecto.</strong> Si te unes a una liga, un crew o un buddy, los demás miembros ven tu usuario, tu rango y tu constancia; un buddy también ve tus anillos y tu racha; los miembros de un crew ven su feed de actividad y sus reacciones. Nunca tu P&amp;L, importes, operaciones ni cuentas. Puedes salir cuando quieras.</li>
<li><strong>Datos del juego:</strong> Sweep guarda tu XP, nivel, rango, insignias, misiones, jefes, rachas, cofres y progreso de temporada para hacer funcionar estas funciones.</li>
<li><strong>Discord:</strong> si conectas Discord, Sweep guarda tu ID y nombre de usuario de Discord y comparte tu rango de Sweep con Discord para asignar un rol en los servidores que lo usen. Al desconectarte se detiene.</li>
<li><strong>Referidos:</strong> Sweep registra quién invitó a quién y si se alcanzó la actividad requerida (10 operaciones en 3 días distintos, o un plan de pago) para conceder las recompensas.</li>
<li><strong>Feedback:</strong> las ideas y reportes de errores que envías desde la app, con su estado, se guardan para darles seguimiento y avisarte cuando estén listos.</li></ul>
<h2>Gráficos</h2><p>Los gráficos muestran datos de mercado de CME, que no contienen información personal.</p>
<h2>Tarjetas para compartir</h2><p>Las tarjetas para compartir se crean en tu dispositivo. No se sube nada salvo que compartas tú mismo la imagen.</p>
<h2>Cuánto tiempo la conservamos</h2><p>Conservamos tu información mientras tu cuenta esté abierta. Si eliminas tu cuenta en Ajustes, tu cuenta y todos sus datos, capturas incluidas, se eliminan al instante. Las direcciones IP se guardan hasta 24 horas.</p>
<h2>Tus derechos</h2><p>Puedes acceder a tu información personal, corregirla o eliminarla, retirar tu consentimiento y recibir tus datos en un formato estructurado de uso común:</p><ul>
<li><strong>Exportar:</strong> un clic te da un archivo ZIP con una copia reimportable, hojas CSV (operaciones, cuentas, payouts, gastos, diario) y todas tus capturas.</li>
<li><strong>Eliminar:</strong> Ajustes → Eliminar mi cuenta (se requiere tu contraseña), o pídenoslo por correo.</li>
<li><strong>Cualquier otra solicitud:</strong> escribe a {M}. Respondemos en un plazo de 30 días.</li></ul>
<p>También puedes presentar una queja ante la Commission d’accès à l’information du Québec.</p>
<h2>Seguridad</h2><p>Sweep usa solo HTTPS, cabeceras de seguridad estrictas, contraseñas con hash, enlaces de restablecimiento de un solo uso válidos una hora, límites de intentos de acceso y protección antibots. Si un incidente de confidencialidad presenta un riesgo de perjuicio grave, te avisaremos a ti y a la Commission d’accès à l’information, como exige la ley.</p>
<h2>Edad</h2><p>Sweep es para mayores de 18 años. Debes confirmar que tienes 18 años o más para crear una cuenta.</p>
<h2>Cambios</h2><p>Publicaremos los cambios en esta página con una nueva fecha de entrada en vigor y anunciaremos los cambios importantes en la app.</p>
""")

TERMS = T(f"""
<h2>Agreement</h2><p>These Terms of use are an agreement between you and <strong>{CO}</strong>, {ADDR} (“Sweep”, “we”). By creating an account or using Sweep, you accept them and our <a href="privacy.html">Privacy policy</a>. If you don’t accept them, don’t use Sweep.</p>
<h2>Eligibility and your account</h2><p>You must be at least 18 years old. Keep your password private; you are responsible for activity on your account. Tell us right away at {M} if you think someone accessed it without permission.</p>
<h2>Plans, billing and cancellation</h2>
<p><strong>Plans.</strong> Sweep offers a Free plan and paid Pro and Elite plans, with the features and limits shown on the <a href="pricing.html">Pricing page</a>. Features and limits may change; if a change reduces what a paid plan includes, we will tell paying users before it applies.</p>
<p><strong>Subscriptions.</strong> Paid plans are billed monthly or yearly in advance, in U.S. dollars, through our payment processor Stripe. They renew automatically until you cancel. You can cancel anytime in Settings → Plan → Manage billing; your plan stays active until the end of the period already paid and does not renew.</p>
<p><strong>Pro at sign-up.</strong> The Free plan is free forever. New accounts get Pro for their first 60 days, with no card required. At the end of those 60 days, the account moves to the Free plan unless you subscribe. Elite is a paid upgrade and is not included in the 60 days.</p>
<p><strong>Founding member offer.</strong> Members who signed up during early access get 50% off for life on Pro or Elite: Pro at $9.50 a month ($79.50 a year) and Elite at $19.50 a month ($164.50 a year). The offer must be taken by December 1, 2026 and applies for as long as that subscription stays active. If a founding subscription is cancelled, it can be restarted at the founding price only before December 1, 2026.</p>
<p><strong>Failed payments.</strong> If a payment fails, your access continues for a grace period of 7 days while the payment is retried. If it still fails, the account moves to the Free plan.</p>
<p><strong>Downgrades.</strong> Moving to a lower plan never deletes your data. Extra accounts become read-only, and some data (such as older analytics) is hidden until you upgrade again.</p>
<p><strong>Refunds.</strong> Payments are non-refundable. When you cancel, your subscription stays active until the end of the period you already paid for and will not renew. No refunds or credits are given for partial periods, unused time or downgrades, except where required by law.</p>
<p><strong>Taxes.</strong> Prices are shown in USD before applicable taxes. Taxes are calculated and added at checkout based on your billing address.</p>
<p><strong>Referrals.</strong> When you invite a friend with your referral link, your friend gets 30 days of Pro, and you get one free month once they use Sweep for real: 10 trades on 3 different days, or a paid plan. You can earn up to 12 free months per year. Self-referrals, fake accounts and abuse cancel the rewards. Free months have no cash value.</p>
<h2>Your data belongs to you</h2><p>You own the trades, notes, screenshots and other information you enter. You give us permission to store, process and display them only to provide Sweep to you. You can export your data (Settings → Export all data) and delete your account (Settings → Delete my account) at any time.</p>
<h2>Limits</h2><p>Each account can store up to 200 MB of screenshots and 50,000 records. Upload only content you have the right to use, and no unlawful content.</p>
<h2>Acceptable use</h2><p>Don’t try to access other users’ data, disrupt or overload the service, bypass its limits or security, reverse engineer it, scrape it, create accounts automatically, or use it for anything illegal.</p>
<h2>Not financial advice</h2><p>Sweep is a tracking and analytics tool. Nothing in Sweep is investment, trading, tax or legal advice, a recommendation or a signal. Statistics, scores and patterns are calculated from the data you enter and may be incomplete or inaccurate. You alone are responsible for your trading decisions. See the <a href="risk.html">Risk disclosure</a>.</p>
<h2>Discipline game and social features</h2><p><strong>Rewards.</strong> XP, levels, ranks, badges, missions, bosses, chests, seasons and other rewards are earned through your journaling process, never through profit. They are virtual, have no cash value, cannot be bought, sold or transferred, and may change. Chest odds are shown in the app; chests are never sold. Rewards that grant days of Pro or streak freezes follow the rules shown in the app.</p>
<p><strong>Social features.</strong> Leagues, crews, the accountability buddy and Discord roles are optional. Other members only see your username, rank and consistency (and, for a buddy, your rings and streak), never your P&amp;L, amounts, trades or accounts. Be respectful: no harassment, hateful content, spam or impersonation in usernames, crew names or reactions. We may remove content, reset rankings affected by abuse or suspend access to social features.</p>
<p><strong>Discord.</strong> If you connect Discord, Sweep uses your Discord account to give you a role matching your Sweep rank on servers that use it. You can disconnect anytime. Discord’s own terms apply to your use of Discord.</p>
<h2>Charts and market data</h2><p>Charts use CME market data and are available 24 hours after the session; they are for reviewing past trades, not for live trading. Charts are powered by TradingView Lightweight Charts™. Prop firm rule presets are prefilled for guidance only; always check your firm’s current rules.</p>
<h2>Sweep AI</h2><p>AI features are optional and included on every plan with the daily and monthly limits of your plan, shown on the Pricing page. AI output (drafts, reviews, feedback, answers and reports) is generated automatically, can be incomplete or wrong, and is never investment advice or a trade recommendation. Check every draft before saving it; you remain responsible for the data you save and the decisions you make. Don’t use the AI features to get around the limits or to submit content you don’t have the right to use.</p>
<h2>Third-party information</h2><p>The economic calendar is built from public schedules (such as the U.S. Bureau of Labor Statistics and the Federal Reserve). Some dates are estimates and marked “est.”. Economic figures and market reports are compiled automatically from public sources and may be delayed, incomplete or wrong. Always check the official release before relying on it. Tradovate import depends on the format of Tradovate’s reports.</p>
<h2>Availability and changes</h2><p>We work to keep Sweep available and your data safe, but the service is provided “as is” and “as available”, without any guarantee that it will be uninterrupted or error-free. We will give reasonable notice of significant changes to these terms.</p>
<h2>Limitation of liability</h2><p>To the extent permitted by law, Sweep Inc. is not liable for trading losses, lost profits, loss of data or indirect damages arising from the use of the service. Nothing in these terms limits rights you have under consumer protection laws that apply to you, including Quebec’s <em>Consumer Protection Act</em>.</p>
<h2>Ending your account</h2><p>You can stop using Sweep and delete your account at any time. We may suspend or close accounts that break these terms; we will tell you why unless the law prevents it.</p>
<h2>Governing law</h2><p>These terms are governed by the laws of Quebec and the federal laws of Canada that apply there. The courts of the judicial district of Laval, Quebec, have jurisdiction, subject to any rights you have as a consumer.</p>
<h2>Contact</h2><p>{CO}, {ADDR}. {M}.</p>
""", f"""
<h2>Entente</h2><p>Les présentes Conditions d’utilisation sont une entente entre toi et <strong>{CO}</strong>, {ADDR} (« Sweep », « nous »). En créant un compte ou en utilisant Sweep, tu les acceptes, ainsi que notre <a href="privacy.html">Politique de confidentialité</a>. Si tu ne les acceptes pas, n’utilise pas Sweep.</p>
<h2>Admissibilité et compte</h2><p>Tu dois avoir au moins 18 ans. Garde ton mot de passe confidentiel; tu es responsable de l’activité sur ton compte. Avise-nous sans délai à {M} si tu crois qu’on y a accédé sans ton autorisation.</p>
<h2>Forfaits, facturation et annulation</h2>
<p><strong>Forfaits.</strong> Sweep offre un forfait Free et des forfaits payants Pro et Elite, avec les fonctionnalités et limites indiquées sur la <a href="pricing.html">page Tarifs</a>. Les fonctionnalités et limites peuvent changer; si un changement réduit ce que comprend un forfait payant, nous en aviserons les abonnés avant qu’il s’applique.</p>
<p><strong>Abonnements.</strong> Les forfaits payants sont facturés chaque mois ou chaque année à l’avance, en dollars américains, par notre processeur de paiement Stripe. Ils se renouvellent automatiquement jusqu’à ce que tu annules. Tu peux annuler en tout temps dans Réglages → Forfait → Gérer la facturation; ton forfait reste actif jusqu’à la fin de la période déjà payée et ne se renouvelle pas.</p>
<p><strong>Pro à l’inscription.</strong> Le forfait Free est gratuit pour toujours. Les nouveaux comptes ont Pro pendant leurs 60 premiers jours, sans carte requise. À la fin de ces 60 jours, le compte passe au forfait Free, sauf si tu t’abonnes. Elite est une montée en gamme payante et n’est pas inclus dans les 60 jours.</p>
<p><strong>Offre Membre fondateur.</strong> Les membres inscrits pendant l’accès anticipé profitent de 50 % de rabais à vie sur Pro ou Elite : Pro à 9,50 $ par mois (79,50 $ par an) et Elite à 19,50 $ par mois (164,50 $ par an). L’offre doit être prise au plus tard le 1er décembre 2026 et s’applique tant que cet abonnement reste actif. Un abonnement fondateur annulé ne peut être repris au prix fondateur qu’avant le 1er décembre 2026.</p>
<p><strong>Paiements refusés.</strong> Si un paiement échoue, ton accès continue pendant une période de grâce de 7 jours pendant que le paiement est retenté. S’il échoue encore, le compte passe au forfait Free.</p>
<p><strong>Changement vers un forfait inférieur.</strong> Passer à un forfait inférieur ne supprime jamais tes données. Les comptes en trop deviennent en lecture seule, et certaines données (comme les analyses plus anciennes) sont masquées jusqu’à ce que tu reviennes au forfait supérieur.</p>
<p><strong>Remboursements.</strong> Les paiements ne sont pas remboursables. Quand tu annules, ton abonnement reste actif jusqu’à la fin de la période déjà payée et ne se renouvelle pas. Aucun remboursement ni crédit n’est accordé pour une période partielle, du temps non utilisé ou un changement vers un forfait inférieur, sauf si la loi l’exige.</p>
<p><strong>Taxes.</strong> Les prix sont affichés en dollars américains, avant les taxes applicables, qui sont calculées et ajoutées au paiement selon ton adresse de facturation.</p>
<p><strong>Parrainage.</strong> Quand tu invites un ami avec ton lien de parrainage, il reçoit 30 jours de Pro, et toi un mois gratuit dès qu’il utilise Sweep pour vrai : 10 trades sur 3 jours différents, ou un forfait payant. Tu peux obtenir jusqu’à 12 mois gratuits par année. L’auto-parrainage, les faux comptes et les abus annulent les récompenses. Les mois gratuits n’ont aucune valeur monétaire.</p>
<h2>Tes données t’appartiennent</h2><p>Tu es propriétaire des trades, notes, captures et autres renseignements que tu saisis. Tu nous autorises à les conserver, traiter et afficher uniquement pour te fournir Sweep. Tu peux exporter tes données (Réglages → Exporter toutes les données) et supprimer ton compte (Réglages → Supprimer mon compte) en tout temps.</p>
<h2>Limites</h2><p>Chaque compte peut conserver jusqu’à 200 Mo de captures et 50 000 enregistrements. Ne téléverse que du contenu que tu as le droit d’utiliser, et aucun contenu illégal.</p>
<h2>Utilisation acceptable</h2><p>N’essaie pas d’accéder aux données d’autres utilisateurs, de perturber ou surcharger le service, de contourner ses limites ou sa sécurité, de le rétroconcevoir, d’en extraire le contenu, de créer des comptes automatiquement ni de l’utiliser à des fins illégales.</p>
<h2>Pas des conseils financiers</h2><p>Sweep est un outil de suivi et d’analyse. Rien dans Sweep ne constitue un conseil en placement, en trading, fiscal ou juridique, une recommandation ou un signal. Les statistiques, scores et tendances sont calculés à partir des données que tu saisis et peuvent être incomplets ou inexacts. Tu es seul responsable de tes décisions de trading. Voir la <a href="risk.html">Divulgation des risques</a>.</p>
<h2>Jeu de discipline et fonctions sociales</h2><p><strong>Récompenses.</strong> L’XP, les niveaux, rangs, badges, missions, boss, coffres, saisons et autres récompenses se gagnent par ton processus de journal, jamais par le profit. Elles sont virtuelles, n’ont aucune valeur monétaire, ne peuvent être achetées, vendues ou transférées, et peuvent changer. Les probabilités des coffres sont affichées dans l’app; les coffres ne sont jamais vendus. Les récompenses qui donnent des jours de Pro ou des gels de streak suivent les règles affichées dans l’app.</p>
<p><strong>Fonctions sociales.</strong> Les ligues, crews, l’accountability buddy et les rôles Discord sont optionnels. Les autres membres ne voient que ton pseudo, ton rang et ta régularité (et, pour un buddy, tes anneaux et ton streak), jamais ton P&amp;L, tes montants, tes trades ou tes comptes. Sois respectueux : aucun harcèlement, contenu haineux, pourriel ni usurpation d’identité dans les pseudos, noms de crew ou réactions. Nous pouvons retirer du contenu, réinitialiser un classement touché par un abus ou suspendre l’accès aux fonctions sociales.</p>
<p><strong>Discord.</strong> Si tu connectes Discord, Sweep utilise ton compte Discord pour te donner un rôle correspondant à ton rang Sweep sur les serveurs qui l’utilisent. Tu peux le déconnecter en tout temps. Les conditions de Discord s’appliquent à ton utilisation de Discord.</p>
<h2>Graphiques et données de marché</h2><p>Les graphiques utilisent les données de marché du CME et sont disponibles 24 h après la séance; ils servent à revoir des trades passés, pas à trader en direct. Les graphiques sont propulsés par TradingView Lightweight Charts™. Les préréglages de règles des prop firms sont préremplis à titre indicatif; vérifie toujours les règles actuelles de ta firme.</p>
<h2>Sweep AI</h2><p>Les fonctions IA sont optionnelles et incluses dans tous les forfaits, avec les limites quotidiennes et mensuelles de ton forfait indiquées sur la page Tarifs. Les résultats de l’IA (brouillons, bilans, avis, réponses et rapports) sont générés automatiquement, peuvent être incomplets ou erronés, et ne constituent jamais un conseil en placement ni une recommandation de trade. Vérifie chaque brouillon avant de l’enregistrer; tu demeures responsable des données que tu enregistres et de tes décisions. N’utilise pas les fonctions IA pour contourner les limites ni pour soumettre du contenu que tu n’as pas le droit d’utiliser.</p>
<h2>Renseignements de tiers</h2><p>Le calendrier économique est bâti à partir de calendriers publics (comme ceux du Bureau of Labor Statistics et de la Réserve fédérale des États-Unis). Certaines dates sont estimées et marquées « est. ». Les chiffres économiques et les rapports de marché sont compilés automatiquement à partir de sources publiques et peuvent être en retard, incomplets ou erronés. Vérifie toujours la publication officielle avant de t’y fier. L’import Tradovate dépend du format des rapports de Tradovate.</p>
<h2>Disponibilité et changements</h2><p>Nous travaillons à garder Sweep disponible et tes données en sécurité, mais le service est fourni « tel quel » et « selon la disponibilité », sans garantie qu’il sera ininterrompu ou exempt d’erreurs. Nous donnerons un préavis raisonnable des changements importants à ces conditions.</p>
<h2>Limitation de responsabilité</h2><p>Dans la mesure permise par la loi, Sweep Inc. n’est pas responsable des pertes de trading, du manque à gagner, de la perte de données ou des dommages indirects découlant de l’utilisation du service. Rien dans ces conditions ne limite les droits que te confèrent les lois de protection du consommateur applicables, dont la <em>Loi sur la protection du consommateur</em> du Québec.</p>
<h2>Fin du compte</h2><p>Tu peux cesser d’utiliser Sweep et supprimer ton compte en tout temps. Nous pouvons suspendre ou fermer un compte qui enfreint ces conditions; nous t’en donnerons la raison, sauf si la loi l’interdit.</p>
<h2>Droit applicable</h2><p>Ces conditions sont régies par les lois du Québec et les lois fédérales du Canada qui s’y appliquent. Les tribunaux du district judiciaire de Laval (Québec) sont compétents, sous réserve des droits que tu as comme consommateur.</p>
<h2>Contact</h2><p>{CO}, {ADDR}. {M}.</p>
""", f"""
<h2>Acuerdo</h2><p>Estos Términos de uso son un acuerdo entre tú y <strong>{CO}</strong>, {ADDR} («Sweep», «nosotros»). Al crear una cuenta o usar Sweep, los aceptas junto con nuestra <a href="privacy.html">Política de privacidad</a>. Si no los aceptas, no uses Sweep.</p>
<h2>Requisitos y cuenta</h2><p>Debes tener al menos 18 años. Mantén tu contraseña en privado; eres responsable de la actividad en tu cuenta. Avísanos de inmediato a {M} si crees que alguien accedió sin permiso.</p>
<h2>Planes, facturación y cancelación</h2>
<p><strong>Planes.</strong> Sweep ofrece un plan Free y los planes de pago Pro y Elite, con las funciones y límites indicados en la <a href="pricing.html">página de Precios</a>. Las funciones y límites pueden cambiar; si un cambio reduce lo que incluye un plan de pago, avisaremos a los suscriptores antes de aplicarlo.</p>
<p><strong>Suscripciones.</strong> Los planes de pago se facturan por mes o por año por adelantado, en dólares estadounidenses, a través de nuestro procesador de pagos Stripe. Se renuevan automáticamente hasta que canceles. Puedes cancelar cuando quieras en Ajustes → Plan → Gestionar facturación; tu plan sigue activo hasta el final del periodo ya pagado y no se renueva.</p>
<p><strong>Pro al registrarte.</strong> El plan Free es gratis para siempre. Las cuentas nuevas tienen Pro durante sus primeros 60 días, sin tarjeta. Al terminar esos 60 días, la cuenta pasa al plan Free salvo que te suscribas. Elite es una mejora de pago y no está incluida en los 60 días.</p>
<p><strong>Oferta Miembro fundador.</strong> Quienes se registraron durante el acceso anticipado tienen un 50 % de descuento de por vida en Pro o Elite: Pro a 9,50 $ al mes (79,50 $ al año) y Elite a 19,50 $ al mes (164,50 $ al año). La oferta debe aceptarse a más tardar el 1 de diciembre de 2026 y se aplica mientras esa suscripción siga activa. Una suscripción fundadora cancelada solo puede reactivarse al precio fundador antes del 1 de diciembre de 2026.</p>
<p><strong>Pagos fallidos.</strong> Si un pago falla, tu acceso continúa durante un periodo de gracia de 7 días mientras se reintenta el cobro. Si sigue fallando, la cuenta pasa al plan Free.</p>
<p><strong>Bajar de plan.</strong> Pasar a un plan inferior nunca elimina tus datos. Las cuentas adicionales quedan en solo lectura y algunos datos (como los análisis más antiguos) se ocultan hasta que vuelvas a mejorar.</p>
<p><strong>Reembolsos.</strong> Los pagos no son reembolsables. Si cancelas, tu suscripción sigue activa hasta el final del periodo ya pagado y no se renueva. No se hacen reembolsos ni créditos por periodos parciales, tiempo no usado o cambios a un plan inferior, salvo cuando la ley lo exija.</p>
<p><strong>Impuestos.</strong> Los precios se muestran en USD antes de los impuestos aplicables, que se calculan y añaden al pagar según tu dirección de facturación.</p>
<p><strong>Referidos.</strong> Cuando invitas a un amigo con tu enlace de referido, recibe 30 días de Pro, y tú un mes gratis en cuanto use Sweep de verdad: 10 operaciones en 3 días distintos, o un plan de pago. Puedes obtener hasta 12 meses gratis al año. Autorreferirse, crear cuentas falsas o abusar anula las recompensas. Los meses gratis no tienen valor monetario.</p>
<h2>Tus datos son tuyos</h2><p>Eres dueño de las operaciones, notas, capturas y demás información que introduces. Nos autorizas a guardarlas, procesarlas y mostrarlas solo para prestarte Sweep. Puedes exportar tus datos (Ajustes → Exportar todos los datos) y eliminar tu cuenta (Ajustes → Eliminar mi cuenta) en cualquier momento.</p>
<h2>Límites</h2><p>Cada cuenta puede guardar hasta 200 MB de capturas y 50.000 registros. Sube solo contenido que tengas derecho a usar y ningún contenido ilegal.</p>
<h2>Uso aceptable</h2><p>No intentes acceder a datos de otros usuarios, interrumpir o sobrecargar el servicio, eludir sus límites o seguridad, aplicar ingeniería inversa, extraer su contenido, crear cuentas de forma automática ni usarlo con fines ilegales.</p>
<h2>No es asesoramiento financiero</h2><p>Sweep es una herramienta de seguimiento y análisis. Nada en Sweep constituye asesoramiento de inversión, trading, fiscal o legal, una recomendación ni una señal. Las estadísticas, puntuaciones y patrones se calculan con los datos que introduces y pueden ser incompletos o inexactos. Eres el único responsable de tus decisiones de trading. Consulta el <a href="risk.html">Aviso de riesgo</a>.</p>
<h2>Juego de disciplina y funciones sociales</h2><p><strong>Recompensas.</strong> La XP, los niveles, rangos, insignias, misiones, jefes, cofres, temporadas y demás recompensas se ganan con tu proceso de registro, nunca con el beneficio. Son virtuales, no tienen valor monetario, no se pueden comprar, vender ni transferir y pueden cambiar. Las probabilidades de los cofres se muestran en la app; los cofres nunca se venden. Las recompensas que dan días de Pro o congelaciones de racha siguen las reglas indicadas en la app.</p>
<p><strong>Funciones sociales.</strong> Las ligas, crews, el accountability buddy y los roles de Discord son opcionales. Los demás miembros solo ven tu usuario, tu rango y tu constancia (y, en el caso de un buddy, tus anillos y tu racha), nunca tu P&amp;L, importes, operaciones ni cuentas. Sé respetuoso: nada de acoso, contenido de odio, spam ni suplantación en usuarios, nombres de crew o reacciones. Podemos retirar contenido, reiniciar clasificaciones afectadas por abusos o suspender el acceso a las funciones sociales.</p>
<p><strong>Discord.</strong> Si conectas Discord, Sweep usa tu cuenta de Discord para darte un rol según tu rango de Sweep en los servidores que lo usen. Puedes desconectarlo cuando quieras. Las condiciones de Discord se aplican a tu uso de Discord.</p>
<h2>Gráficos y datos de mercado</h2><p>Los gráficos usan datos de mercado de CME y están disponibles 24 horas después de la sesión; sirven para revisar operaciones pasadas, no para operar en directo. Los gráficos están impulsados por TradingView Lightweight Charts™. Las reglas predefinidas de las prop firms están precargadas a título indicativo; verifica siempre las reglas actuales de tu firma.</p>
<h2>Sweep AI</h2><p>Las funciones de IA son opcionales y están incluidas en todos los planes, con los límites diarios y mensuales de tu plan indicados en la página de Precios. Los resultados de la IA (borradores, revisiones, opiniones, respuestas e informes) se generan automáticamente, pueden ser incompletos o erróneos y nunca son asesoramiento de inversión ni una recomendación de operación. Revisa cada borrador antes de guardarlo; sigues siendo responsable de los datos que guardas y de tus decisiones. No uses las funciones de IA para eludir los límites ni para enviar contenido que no tengas derecho a usar.</p>
<h2>Información de terceros</h2><p>El calendario económico se basa en calendarios públicos (como los del Bureau of Labor Statistics y la Reserva Federal de EE. UU.). Algunas fechas son estimadas y se marcan «est.». Las cifras económicas y los informes de mercado se compilan automáticamente desde fuentes públicas y pueden llegar tarde, estar incompletos o ser erróneos. Verifica siempre la publicación oficial antes de basarte en ellos. La importación de Tradovate depende del formato de sus informes.</p>
<h2>Disponibilidad y cambios</h2><p>Trabajamos para mantener Sweep disponible y tus datos seguros, pero el servicio se ofrece «tal cual» y «según disponibilidad», sin garantía de que sea ininterrumpido o sin errores. Avisaremos con antelación razonable de los cambios importantes a estos términos.</p>
<h2>Limitación de responsabilidad</h2><p>En la medida permitida por la ley, Sweep Inc. no es responsable de pérdidas de trading, lucro cesante, pérdida de datos ni daños indirectos derivados del uso del servicio. Nada en estos términos limita los derechos que te otorguen las leyes de protección al consumidor aplicables, incluida la ley de protección al consumidor de Quebec.</p>
<h2>Cierre de la cuenta</h2><p>Puedes dejar de usar Sweep y eliminar tu cuenta en cualquier momento. Podemos suspender o cerrar cuentas que incumplan estos términos; te diremos el motivo, salvo que la ley lo impida.</p>
<h2>Ley aplicable</h2><p>Estos términos se rigen por las leyes de Quebec y las leyes federales de Canadá aplicables allí. Son competentes los tribunales del distrito judicial de Laval (Quebec), sin perjuicio de tus derechos como consumidor.</p>
<h2>Contacto</h2><p>{CO}, {ADDR}. {M}.</p>
""")

RISK = T("""
<h2>Futures trading is risky</h2><p>Trading futures and other leveraged products involves substantial risk of loss and is not suitable for every investor. You can lose more than your initial deposit. Only trade with money you can afford to lose.</p>
<h2>No advice, no signals</h2><p>Sweep is a tracking and analytics tool. It does not provide investment, trading, tax or legal advice, and it never recommends or signals a trade. Every decision you make is your own.</p>
<h2>Discipline, not profit</h2><p>Sweep’s game rewards your process (planning, following your rules, reviewing), never profit. Rewards, ranks and streaks say nothing about future results.</p>
<h2>Charts</h2><p>Charts use CME market data available 24 hours after the session. They are for reviewing past trades, not for live trading.</p>
<h2>Share cards</h2><p>Share cards show a user’s own past results. They are not performance claims by Sweep.</p>
<h2>Sweep AI and market reports</h2><p>Sweep AI and the market reports describe past data and public news. They are not trade recommendations.</p>
<h2>Past performance</h2><p>Statistics, scores and patterns in Sweep describe the past, based on data you entered. Past performance, real or simulated, does not guarantee future results.</p>
<h2>Sample data</h2><p>Screenshots and numbers on this website use built-in sample data for illustration only. They are not real results and do not represent the performance of any trader. Firm names shown in screenshots are fictional.</p>
<h2>Prop firms</h2><p>Sweep is not affiliated with, endorsed by or connected to any proprietary trading firm, broker or exchange. Product and company names belong to their respective owners.</p>
""","""
<h2>Le trading de futures est risqué</h2><p>Le trading de contrats à terme et d’autres produits à effet de levier comporte un risque important de perte et ne convient pas à tous les investisseurs. Tu peux perdre plus que ton dépôt initial. Ne trade qu’avec de l’argent que tu peux te permettre de perdre.</p>
<h2>Ni conseils ni signaux</h2><p>Sweep est un outil de suivi et d’analyse. Il ne fournit aucun conseil en placement, en trading, fiscal ou juridique, et ne recommande ni ne signale jamais de trade. Chaque décision t’appartient.</p>
<h2>La discipline, pas le profit</h2><p>Le jeu de Sweep récompense ton processus (planifier, respecter tes règles, réviser), jamais le profit. Les récompenses, rangs et streaks ne disent rien des résultats futurs.</p>
<h2>Graphiques</h2><p>Les graphiques utilisent des données de marché du CME disponibles 24 h après la séance. Ils servent à revoir des trades passés, pas à trader en direct.</p>
<h2>Cartes à partager</h2><p>Les cartes à partager montrent les résultats passés de l’utilisateur. Ce ne sont pas des affirmations de performance de Sweep.</p>
<h2>Sweep AI et rapports de marché</h2><p>Sweep AI et les rapports de marché décrivent des données passées et des nouvelles publiques. Ce ne sont pas des recommandations de trade.</p>
<h2>Performances passées</h2><p>Les statistiques, scores et tendances de Sweep décrivent le passé, selon les données que tu as saisies. Les performances passées, réelles ou simulées, ne garantissent pas les résultats futurs.</p>
<h2>Données d’exemple</h2><p>Les captures et chiffres de ce site utilisent des données d’exemple intégrées, à titre d’illustration seulement. Ce ne sont pas des résultats réels et ils ne représentent la performance d’aucun trader. Les noms de firmes dans les captures sont fictifs.</p>
<h2>Prop firms</h2><p>Sweep n’est affilié à aucune firme de trading pour compte propre, aucun courtier ni aucune bourse, et n’est approuvé par aucun d’eux. Les noms de produits et d’entreprises appartiennent à leurs propriétaires.</p>
""","""
<h2>Operar futuros es arriesgado</h2><p>Operar futuros y otros productos apalancados implica un riesgo sustancial de pérdida y no es adecuado para todos los inversores. Puedes perder más que tu depósito inicial. Opera solo con dinero que puedas permitirte perder.</p>
<h2>Sin consejos ni señales</h2><p>Sweep es una herramienta de seguimiento y análisis. No ofrece asesoramiento de inversión, trading, fiscal ni legal, y nunca recomienda ni señala una operación. Cada decisión es tuya.</p>
<h2>Disciplina, no beneficio</h2><p>El juego de Sweep premia tu proceso (planificar, cumplir tus reglas, revisar), nunca el beneficio. Las recompensas, rangos y rachas no dicen nada de los resultados futuros.</p>
<h2>Gráficos</h2><p>Los gráficos usan datos de mercado de CME disponibles 24 horas después de la sesión. Sirven para revisar operaciones pasadas, no para operar en directo.</p>
<h2>Tarjetas para compartir</h2><p>Las tarjetas para compartir muestran resultados pasados del propio usuario. No son afirmaciones de rendimiento de Sweep.</p>
<h2>Sweep AI e informes de mercado</h2><p>Sweep AI y los informes de mercado describen datos pasados y noticias públicas. No son recomendaciones de operación.</p>
<h2>Resultados pasados</h2><p>Las estadísticas, puntuaciones y patrones de Sweep describen el pasado, según los datos que introdujiste. Los resultados pasados, reales o simulados, no garantizan resultados futuros.</p>
<h2>Datos de ejemplo</h2><p>Las capturas y cifras de este sitio usan datos de ejemplo integrados solo con fines ilustrativos. No son resultados reales ni representan el rendimiento de ningún trader. Los nombres de firmas en las capturas son ficticios.</p>
<h2>Prop firms</h2><p>Sweep no está afiliado, respaldado ni vinculado a ninguna prop firm, bróker o bolsa. Los nombres de productos y empresas pertenecen a sus propietarios.</p>
""")

def legal(title, desc, content):
    def f(lang, t):
        eff = t(T("Effective October 3, 2026 · Sweep Inc.","En vigueur le 3 octobre 2026 · Sweep Inc.","Vigente desde el 3 de octubre de 2026 · Sweep Inc."))
        b = f'<div class="page-hero"><div class="wrap"><span class="kick">{t(T("Legal","Légal","Legal"))}</span><h1>{t(title)}</h1><p class="meta">{eff}</p></div></div><section style="padding-top:8px"><div class="wrap"><div class="legal">{t(content)}</div></div></section>'
        return (t(title) + " · Sweep", t(desc), b, "")
    return f

page_privacy = legal(T("Privacy policy","Politique de confidentialité","Política de privacidad"), T("How Sweep Inc. collects, uses, stores and protects your personal information, and your rights under Quebec’s Law 25.","Comment Sweep Inc. recueille, utilise, conserve et protège tes renseignements personnels, et tes droits selon la Loi 25.","Cómo Sweep Inc. recopila, usa, guarda y protege tu información personal, y tus derechos según la Ley 25 de Quebec."), PRIVACY)
page_terms = legal(T("Terms of use","Conditions d’utilisation","Términos de uso"), T("The terms that apply when you use Sweep, including plans, billing, cancellation, your data and limits.","Les conditions qui s’appliquent à l’utilisation de Sweep, dont les forfaits, la facturation, l’annulation, tes données et les limites.","Los términos que se aplican al usar Sweep, incluidos los planes, la facturación, la cancelación, tus datos y los límites."), TERMS)
page_risk = legal(T("Risk disclosure","Divulgation des risques","Aviso de riesgo"), T("Important information about the risks of trading futures and the sample data shown on this site.","Renseignements importants sur les risques du trading de futures et les données d’exemple de ce site.","Información importante sobre los riesgos de operar futuros y los datos de ejemplo de este sitio."), RISK)
