from core import *
TODAY2 = '2026-10-03'
import re
from pages3 import AI_FAQ


FAQ = [
 (T("Free and plans","Gratuit et forfaits","Gratis y planes"), [
  (T("Is Sweep really free?","Sweep est-il vraiment gratuit ?","¿Sweep es realmente gratis?"),
   T("Yes. The Free plan is free forever. You also get Pro for your first 60 days to try everything, no credit card needed.",
     "Oui. Le forfait Free est gratuit pour toujours. Tu as aussi accès à Pro pendant tes 60 premiers jours pour tout essayer, sans carte de crédit.",
     "Sí. El plan Free es gratis para siempre. También tienes Pro durante tus primeros 60 días para probarlo todo, sin tarjeta.")),
  (T("What happens after the 60 days of Pro?","Que se passe-t-il après les 60 jours de Pro ?","¿Qué pasa después de los 60 días de Pro?"),
   T("You move to the Free plan automatically. Nothing is charged and nothing is lost. Upgrade only if you want to.",
     "Tu passes automatiquement au forfait Free. Rien n’est facturé et rien n’est perdu. Tu passes à un forfait payant seulement si tu le veux.",
     "Pasas automáticamente al plan Free. No se cobra nada y no se pierde nada. Mejora solo si quieres.")),
  (T("Do you offer refunds?","Offrez-vous des remboursements ?","¿Ofrecen reembolsos?"),
   T("All sales are final — that’s why every account gets 60 days of Pro first. You can cancel anytime and keep using Sweep on the Free plan, without losing your data.","Toutes les ventes sont finales : c’est pour ça que chaque compte reçoit d’abord 60 jours de Pro. Tu peux annuler à tout moment et continuer sur le forfait Free, sans perdre tes données.","Todas las ventas son finales: por eso cada cuenta recibe primero 60 días de Pro. Puedes cancelar cuando quieras y seguir en el plan Free sin perder tus datos.")),
  (T("Does Sweep know my firm’s payout rules?","Sweep connaît-il les règles de payout de ma firme ?","¿Sweep conoce las reglas de payout de mi firma?"),
   T("Yes, for Apex, Topstep, Lucid, Take Profit Trader, MyFundedFutures, Tradeify and Alpha Futures: minimum winning days, cushion, minimum and maximum per payout. They’re checked every week, prefilled for guidance and editable by hand.",
     "Oui, pour Apex, Topstep, Lucid, Take Profit Trader, MyFundedFutures, Tradeify et Alpha Futures : jours gagnants minimum, coussin, minimum et maximum par payout. Elles sont vérifiées chaque semaine, préremplies à titre indicatif et modifiables à la main.",
     "Sí, para Apex, Topstep, Lucid, Take Profit Trader, MyFundedFutures, Tradeify y Alpha Futures: días ganadores mínimos, colchón, mínimo y máximo por payout. Se revisan cada semana, vienen precargadas a título indicativo y se pueden editar a mano.")),
  (T("I copy trades across several accounts. How does it work?","Je fais du copy trading sur plusieurs comptes ?","Copio operaciones en varias cuentas, ¿cómo funciona?"),
   T("Choose “Also on” when you add the trade. It appears once, with the total of all accounts, and counts as one decision in your stats.",
     "Choisis « Aussi sur » à l’ajout. Le trade apparaît une seule fois, avec le total de tous les comptes, et compte comme une seule décision dans tes statistiques.",
     "Elige «También en» al añadir la operación. Aparece una sola vez, con el total de todas las cuentas, y cuenta como una sola decisión en tus estadísticas.")),
  (T("What’s the difference between simulated and real money?","Quelle différence entre l’argent simulé et l’argent réel ?","¿Qué diferencia hay entre dinero simulado y real?"),
   T("Profits on evaluation and funded accounts are labeled Simulated; live and personal accounts are Real. My money only counts what you actually received: payouts paid plus live and personal P&L, minus your expenses. Sweep never adds simulated and real together.",
     "Les profits des comptes d’évaluation et financés sont étiquetés Simulé ; les comptes live et perso sont Réel. Mon argent ne compte que ce que tu as vraiment reçu : les payouts payés plus le P&L live et perso, moins tes dépenses. Sweep n’additionne jamais le simulé et le réel.",
     "Las ganancias de las cuentas de evaluación y fondeadas se marcan como Simulado; las cuentas live y personales son Real. Mi dinero solo cuenta lo que realmente recibiste: payouts pagados más el P&L live y personal, menos tus gastos. Sweep nunca suma lo simulado y lo real.")),
  (T("I trade with several prop firms. Does it work?","Je trade avec plusieurs prop firms, ça marche ?","Opero con varias prop firms, ¿funciona?"),
   T("Yes. Add as many accounts as your plan allows, each with its own rules, and copy a trade to several accounts at once.",
     "Oui. Ajoute autant de comptes que ton forfait le permet, chacun avec ses propres règles, et copie un trade sur plusieurs comptes en une fois.",
     "Sí. Añade tantas cuentas como permita tu plan, cada una con sus propias reglas, y copia una operación en varias cuentas a la vez.")),
 ]),
 (T("Charts and trades","Graphiques et trades","Gráficos y operaciones"), [
  (T("How long does it take to log a trade?","Combien de temps faut-il pour ajouter un trade ?","¿Cuánto se tarda en registrar una operación?"),
   T("A few seconds. Paste a screenshot of your platform and Sweep AI fills the trade, or enter it by hand. You check, answer your discipline checklist and save.",
     "Quelques secondes. Colle une capture de ta plateforme et Sweep AI remplit le trade, ou ajoute-le à la main. Tu vérifies, tu réponds à ta checklist de discipline et tu enregistres.",
     "Unos segundos. Pega una captura de tu plataforma y Sweep AI completa la operación, o añádela a mano. Revisas, respondes tu checklist de disciplina y guardas.")),
  (T("I prefer screenshots. How does it work?","Je préfère les captures d’écran, comment ça marche ?","Prefiero las capturas, ¿cómo funciona?"),
   T("Choose “With a screenshot” on your first trade. Sweep AI fills the trade from your screenshot; you can switch to manual anytime.",
     "Choisis « Avec une capture d’écran » au premier ajout. Sweep AI remplit le trade à partir de ta capture, et tu peux passer au manuel à tout moment.",
     "Elige «Con una captura» en tu primera operación. Sweep AI completa la operación a partir de tu captura y puedes pasar al modo manual cuando quieras.")),
  (T("My P&L in Sweep is different from my platform. What do I do?","Mon P&L dans Sweep diffère de ma plateforme ?","Mi P&L en Sweep es distinto al de mi plataforma, ¿qué hago?"),
   T("Enter the “Real P&L (platform)” on the trade, or your commission per contract on the account. For an older gap, use “Recalibrate” on the account page.",
     "Entre le « P&L réel (plateforme) » sur le trade, ou ta commission par contrat sur le compte. Pour un ancien écart, utilise « Recalibrer » sur la page du compte.",
     "Introduce el «P&L real (plataforma)» en la operación, o tu comisión por contrato en la cuenta. Para una diferencia antigua, usa «Recalibrar» en la página de la cuenta.")),
  (T("Are the charts real-time?","Les graphiques sont-ils en temps réel ?","¿Los gráficos son en tiempo real?"),
   T("No. The charts use real CME data and are available 24 hours after each session. They’re for reviewing your trades, not for trading live.",
     "Non. Les graphiques utilisent les vraies données du CME et sont disponibles 24 h après chaque séance. Ils servent à revoir tes trades, pas à trader en direct.",
     "No. Los gráficos usan datos reales de CME y están disponibles 24 horas después de cada sesión. Sirven para revisar tus operaciones, no para operar en directo.")),
  (T("Which instruments are supported?","Quels instruments sont pris en charge ?","¿Qué instrumentos son compatibles?"),
   T("NQ, MNQ, ES, MES, YM, MYM, RTY, M2K, CL, MCL, GC, MGC, SI and 6E. Other instruments can still be journaled, without a chart for now.",
     "NQ, MNQ, ES, MES, YM, MYM, RTY, M2K, CL, MCL, GC, MGC, SI et 6E. Les autres instruments restent journalisables, sans graphique pour l’instant.",
     "NQ, MNQ, ES, MES, YM, MYM, RTY, M2K, CL, MCL, GC, MGC, SI y 6E. Los demás instrumentos se pueden registrar, sin gráfico por ahora.")),
  (T("Do my trades sync with my platform?","Mes trades se synchronisent-ils avec ma plateforme ?","¿Mis operaciones se sincronizan con mi plataforma?"),
   T("Add trades from a screenshot, in your own words, or by importing your platform’s export. Automatic live sync with Rithmic and Tradovate is in development.","Ajoute tes trades par capture, avec tes mots ou en important l’export de ta plateforme. La synchronisation automatique avec Rithmic et Tradovate est en développement.","Agrega operaciones con una captura, con tus palabras o importando la exportación de tu plataforma. La sincronización automática con Rithmic y Tradovate está en desarrollo.")),
 ]),
 (T("Privacy and approach","Confidentialité et approche","Privacidad y enfoque"), [
  (T("Can other users see my results?","Est-ce que d’autres utilisateurs voient mes résultats ?","¿Otros usuarios ven mis resultados?"),
   T("Never. Leagues, crews and buddies are optional and only show your username, your rank and your consistency. No P&L, no amounts, no trades.",
     "Jamais. Les ligues, crews et buddies sont optionnels et ne montrent que ton pseudo, ton rang et ta régularité. Aucun P&L, aucun montant, aucun trade.",
     "Nunca. Las ligas, crews y buddies son opcionales y solo muestran tu usuario, tu rango y tu constancia. Ningún P&L, ningún importe, ninguna operación.")),
  (T("Why reward discipline and not profit?","Pourquoi récompenser la discipline et pas le profit ?","¿Por qué premiar la disciplina y no el beneficio?"),
   T("Because a day’s profit partly depends on chance, while discipline is built. Sweep rewards what you control.",
     "Parce que le profit d’une journée dépend en partie du hasard, alors que la discipline se construit. Sweep récompense ce que tu contrôles.",
     "Porque el beneficio de un día depende en parte del azar, mientras que la disciplina se construye. Sweep premia lo que controlas.")),
  (T("Does Sweep give trading advice?","Sweep donne-t-il des conseils de trading ?","¿Sweep da consejos de trading?"),
   T("No. Sweep and Sweep AI help you analyze your own behavior. They are never financial advice.",
     "Non. Sweep et Sweep AI t’aident à analyser ton propre comportement. Ce ne sont jamais des conseils financiers.",
     "No. Sweep y Sweep AI te ayudan a analizar tu propio comportamiento. Nunca son asesoramiento financiero.")),
  (T("How do I share my stats?","Comment partager mes stats ?","¿Cómo comparto mis estadísticas?"),
   T("From the Stats page: as an image with your name, or as a read-only link to your Stats page. The link shows only what you chose, and you can delete it anytime.",
     "Depuis la page Stats : en image (avec ton nom) ou en lien vers ta page Stats en lecture seule. Le lien montre seulement ce que tu as choisi, et tu peux le supprimer à tout moment.",
     "Desde la página de Stats: como imagen con tu nombre o como enlace de solo lectura a tu página de Stats. El enlace muestra solo lo que elegiste y puedes borrarlo cuando quieras.")),
  (T("A question?","Une question ?","¿Una pregunta?"),
   T("Write to hello@makeitsweep.com: we answer every message.","Écris à hello@makeitsweep.com : on répond à chaque message.","Escribe a hello@makeitsweep.com: respondemos a cada mensaje.")),
  (T("Can I get my data back?","Puis-je récupérer mes données ?","¿Puedo recuperar mis datos?"),
   T("Yes, in one click: a ZIP file with your whole history, your spreadsheets and your screenshots.",
     "Oui, en un clic : un fichier ZIP avec tout ton historique, tes tableurs et tes captures.",
     "Sí, en un clic: un archivo ZIP con todo tu historial, tus hojas de cálculo y tus capturas.")),
 ]),
]

def page_faq(lang, t):
    groups = "".join(f'<div class="faq-group"><h2>{t(c)}</h2>' + "".join(faq_item(t,q,a) for q,a in items) + "</div>" for c, items in FAQ)
    ld = jsonld({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":t(q),"acceptedAnswer":{"@type":"Answer","text":t(a)}} for _,items in FAQ for q,a in items]})
    body = page_hero(t, T("Questions and answers.","Questions et réponses.","Preguntas y respuestas."),
        T(f"Everything about Sweep, your data and prop accounts. Can’t find it? Write to {EMAIL}.", f"Tout sur Sweep, tes données et tes comptes prop. Tu ne trouves pas? Écris à {EMAIL}.", f"Todo sobre Sweep, tus datos y cuentas prop. ¿No lo encuentras? Escribe a {EMAIL}."), T("FAQ","FAQ","Preguntas frecuentes"))
    body += f'<section style="padding-top:24px"><div class="wrap narrow">{groups}</div></section>'
    return (t(T("FAQ · Sweep trading journal","FAQ · Journal de trading Sweep","Preguntas frecuentes · Diario de trading Sweep")),
            t(T("Answers about Sweep: free plan and 60 days of Pro, real CME charts, instruments, prop firms, privacy, refunds and your data.","Réponses sur Sweep : forfait gratuit et 60 jours de Pro, vrais graphiques CME, instruments, prop firms, confidentialité, remboursements et tes données.","Respuestas sobre Sweep: plan gratuito y 60 días de Pro, gráficos reales de CME, instrumentos, prop firms, privacidad, reembolsos y tus datos.")),
            body + final_cta(lang, t), ld)

INDICATORS = ["CPI","Core CPI","PPI","PCE","Nonfarm Payrolls","Unemployment rate","Average hourly earnings","Initial jobless claims","ADP employment","JOLTS","GDP","Retail sales","ISM Manufacturing","ISM Services","Consumer confidence","FOMC decision","FOMC minutes"]
def page_econ(lang, t):
    hero = page_hero(t, T("An economic calendar that knows your trades.","Un calendrier économique qui connaît tes trades.","Un calendario económico que conoce tus operaciones."),
        T("High and medium impact U.S. releases in Eastern Time, linked to every trade you log. See how you really trade CPI, NFP and FOMC days.","Les publications américaines d’impact élevé et moyen en heure de l’Est, liées à chaque trade que tu notes. Vois comment tu trades vraiment les journées CPI, NFP et FOMC.","Publicaciones de EE. UU. de impacto alto y medio en hora del Este, vinculadas a cada operación. Mira cómo operas de verdad los días de CPI, NFP y FOMC."),
        T("Economic calendar","Calendrier économique","Calendario económico"), f'<a class="btn btn-primary btn-lg" href="{SIGNUP}">{t(CREATE_FREE)}</a>')
    b = f'<section style="padding-top:16px"><div class="wrap">{frame("economic-calendar",lang,t(T("Economic calendar in Sweep","Calendrier économique dans Sweep","Calendario económico en Sweep")),t,eager=True)}</div></section>'
    b += split(t, T("On your trades","Sur tes trades","En tus operaciones"), T("Every trade knows what was released around it.","Chaque trade sait ce qui est sorti autour.","Cada operación sabe qué se publicó a su alrededor."),
      T("Sweep links each saved trade to the U.S. events from 30 minutes before entry to 30 minutes after exit, and shows the timing, for example “2m 00s after the release”.","Sweep lie chaque trade aux événements américains de 30 minutes avant l’entrée à 30 minutes après la sortie, et montre le délai, par exemple « 2 min 00 s après la publication ».","Sweep vincula cada operación a los eventos de EE. UU. desde 30 minutos antes de la entrada hasta 30 después de la salida, y muestra el tiempo, por ejemplo «2 min 00 s después de la publicación»."),
      [T("A warning in the trade ticket when a release is close","Un avertissement dans le ticket quand une publication approche","Un aviso en el ticket cuando se acerca una publicación"),
       T("News on the time axis of every trade chart","Les nouvelles sur l’axe du temps de chaque graphique","Las noticias en el eje del tiempo de cada gráfico"),
       T("High-impact events in each day of the P&L calendar","Les événements importants dans chaque jour du calendrier P&L","Eventos de alto impacto en cada día del calendario de P&L"),
       T("Insights on trades within 5 or 15 minutes of a release versus the rest","Analyses des trades à 5 ou 15 minutes d’une publication par rapport aux autres","Análisis de operaciones a 5 o 15 minutos de una publicación frente al resto")],
      frame("calendar",lang,t(T("P&L calendar with daily news","Calendrier P&L avec les nouvelles du jour","Calendario de P&L con noticias del día")),t))
    b += split(t, T("Event detail","Détail d’un événement","Detalle del evento"), T("Understand the number before it hits.","Comprends le chiffre avant qu’il tombe.","Entiende el dato antes de que salga."),
      T("Open any event for its values, the surprise against the forecast, the revision to the previous value, a plain explainer of the indicator and its release history.","Ouvre n’importe quel événement pour ses valeurs, la surprise par rapport à la prévision, la révision de la valeur précédente, une explication claire de l’indicateur et son historique.","Abre cualquier evento para ver sus valores, la sorpresa frente al pronóstico, la revisión del dato anterior, una explicación clara del indicador y su historial."),
      [], frame("event-detail",lang,t(T("Event detail panel","Panneau de détail d’un événement","Panel de detalle del evento")),t), flip=True,
      more='<div class="chips" style="margin-top:26px">' + "".join(f"<span>{i}</span>" for i in INDICATORS) + "</div>")
    rows = [(T("Scope","Portée","Alcance"),T("U.S. events, high and medium impact","Événements américains, impact élevé et moyen","Eventos de EE. UU., impacto alto y medio")),
            (T("Time zone","Fuseau horaire","Zona horaria"),T("Eastern Time (New York)","Heure de l’Est (New York)","Hora del Este (Nueva York)")),
            (T("Views","Vues","Vistas"),T("Today, tomorrow, this week, next week","Aujourd’hui, demain, cette semaine, la semaine prochaine","Hoy, mañana, esta semana, la próxima")),
            (T("Source","Source","Fuente"),T("BLS and Federal Reserve calendars, 2026–2027","Calendriers du BLS et de la Réserve fédérale, 2026–2027","Calendarios del BLS y la Reserva Federal, 2026–2027")),
            (T("“est.”","« est. »","«est.»"),T("Dates projected from the usual release pattern, until the official date is published","Dates projetées selon le rythme habituel des publications, en attendant la date officielle","Fechas proyectadas según el patrón habitual, hasta que se publique la fecha oficial")),
            (T("Values","Valeurs","Valores"),T("Actual, forecast and previous are shown when available for an event","Réel, prévision et précédent sont affichés quand ils sont disponibles","Real, pronóstico y anterior se muestran cuando están disponibles"))]
    b += f'<section class="rule"><div class="wrap narrow"><div class="head"><h2>{t(T("What’s covered","Ce qui est couvert","Qué cubre"))}</h2></div><table class="tbl"><tbody>' + "".join(f"<tr><th>{t(a)}</th><td>{t(c)}</td></tr>" for a,c in rows) + "</tbody></table></div></section>"
    return (t(T("Economic calendar for futures traders · CPI, NFP, FOMC · Sweep","Calendrier économique pour traders de futures · CPI, NFP, FOMC · Sweep","Calendario económico para traders de futuros · CPI, NFP, FOMC · Sweep")),
            t(T("U.S. high and medium impact economic events in Eastern Time, linked to your trades. See your results around CPI, NFP, FOMC and 16 other indicators.","Événements économiques américains d’impact élevé et moyen en heure de l’Est, liés à tes trades. Vois tes résultats autour du CPI, du NFP, du FOMC et de 16 autres indicateurs.","Eventos económicos de EE. UU. de impacto alto y medio en hora del Este, vinculados a tus operaciones. Mira tus resultados alrededor de CPI, NFP, FOMC y 16 indicadores más.")),
            hero + b + final_cta(lang, t), "")

def howto_page(lang, t, title, lead, kick, steps, media, seo_t, seo_d, extra=""):
    lis = "".join(f"<li><div>{t(s)}</div></li>" for s in steps)
    hero = page_hero(t, title, lead, kick)
    b = f'<section style="padding-top:16px"><div class="wrap split"><div class="copy"><ol class="howto">{lis}</ol>{extra}</div><div class="reveal">{media}</div></div></section>'
    ld = jsonld({"@context":"https://schema.org","@type":"HowTo","name":t(title),"step":[{"@type":"HowToStep","position":i+1,"text":re.sub("<[^>]+>","",t(s))} for i,s in enumerate(steps)]})
    return (t(seo_t), t(seo_d), hero + b + final_cta(lang, t), ld)

def page_tradovate(lang, t):
    steps = [T("In Tradovate, set your time zone to <b>New York</b> so times match Sweep.","Dans Tradovate, règle ton fuseau horaire sur <b>New York</b> pour que les heures concordent avec Sweep.","En Tradovate, pon tu zona horaria en <b>Nueva York</b> para que las horas coincidan con Sweep."),
             T("Open the <b>Performance</b> report for the period you want and export it as <b>CSV</b>.","Ouvre le rapport <b>Performance</b> pour la période voulue et exporte-le en <b>CSV</b>.","Abre el informe <b>Performance</b> del periodo que quieras y expórtalo en <b>CSV</b>."),
             T("In Sweep, go to <b>Trades → Import CSV</b> and choose the file.","Dans Sweep, va dans <b>Trades → Importer un CSV</b> et choisis le fichier.","En Sweep, ve a <b>Operaciones → Importar CSV</b> y elige el archivo."),
             T("Check the <b>preview</b>, pick the account, then import. Fills of the same entry are grouped into one trade.","Vérifie l’<b>aperçu</b>, choisis le compte, puis importe. Les exécutions d’une même entrée sont regroupées en un seul trade.","Revisa la <b>vista previa</b>, elige la cuenta e importa. Las ejecuciones de una misma entrada se agrupan en una operación."),
             T("Import again any time: trades already in Sweep are <b>skipped</b>, never duplicated.","Réimporte quand tu veux : les trades déjà dans Sweep sont <b>ignorés</b>, jamais en double.","Importa de nuevo cuando quieras: las operaciones ya en Sweep se <b>omiten</b>, nunca se duplican.")]
    return howto_page(lang, t, T("Import your trades from Tradovate.","Importe tes trades depuis Tradovate.","Importa tus operaciones desde Tradovate."),
        T("Bring your history into Sweep in a few minutes with the Tradovate Performance report.","Amène ton historique dans Sweep en quelques minutes avec le rapport Performance de Tradovate.","Trae tu historial a Sweep en unos minutos con el informe Performance de Tradovate."),
        T("Help","Aide","Ayuda"), steps, frame("trades",lang,t(T("Trades list after import","Liste des trades après l’import","Lista de operaciones tras importar")),t),
        T("Import trades from Tradovate CSV · Sweep","Importer ses trades Tradovate en CSV · Sweep","Importar operaciones de Tradovate en CSV · Sweep"),
        T("How to export the Tradovate Performance report as CSV and import it into the Sweep trading journal without duplicates.","Comment exporter le rapport Performance de Tradovate en CSV et l’importer dans le journal Sweep sans doublons.","Cómo exportar el informe Performance de Tradovate en CSV e importarlo en el diario Sweep sin duplicados."),
        f'<p class="meta" style="margin-top:28px">{t(T("Other brokers: log trades in the ticket for now. Automatic broker sync is not available today.","Autres courtiers : note tes trades dans le ticket pour l’instant. La synchronisation automatique n’est pas encore offerte.","Otros brókers: registra las operaciones en el ticket por ahora. La sincronización automática aún no está disponible."))}</p>')

def page_install(lang, t):
    ios = [T("Open <b>app.makeitsweep.com</b> in <b>Safari</b> and log in.","Ouvre <b>app.makeitsweep.com</b> dans <b>Safari</b> et connecte-toi.","Abre <b>app.makeitsweep.com</b> en <b>Safari</b> e inicia sesión."),
           T("Tap <b>Share</b>, then <b>Add to Home Screen</b>.","Touche <b>Partager</b>, puis <b>Sur l’écran d’accueil</b>.","Toca <b>Compartir</b> y luego <b>Añadir a pantalla de inicio</b>."),
           T("Open Sweep from its icon. It runs full screen, like an app.","Ouvre Sweep depuis son icône. Il s’ouvre en plein écran, comme une app.","Abre Sweep desde su icono. Funciona a pantalla completa, como una app.")]
    andr = [T("Open <b>app.makeitsweep.com</b> in <b>Chrome</b> and log in.","Ouvre <b>app.makeitsweep.com</b> dans <b>Chrome</b> et connecte-toi.","Abre <b>app.makeitsweep.com</b> en <b>Chrome</b> e inicia sesión."),
            T("Tap <b>⋮</b>, then <b>Install app</b>.","Touche <b>⋮</b>, puis <b>Installer l’application</b>.","Toca <b>⋮</b> y luego <b>Instalar app</b>."),
            T("Sweep appears with your other apps.","Sweep apparaît avec tes autres apps.","Sweep aparece con tus otras apps.")]
    ol = lambda xs: '<ol class="howto">' + "".join(f"<li><div>{t(s)}</div></li>" for s in xs) + "</ol>"
    hero = page_hero(t, T("Sweep on your home screen.","Sweep sur ton écran d’accueil.","Sweep en tu pantalla de inicio."),
        T("No App Store needed. Install Sweep from your browser in three taps and open it like any other app.","Pas besoin de l’App Store. Installe Sweep depuis ton navigateur en trois touchers et ouvre-le comme n’importe quelle app.","Sin App Store. Instala Sweep desde el navegador en tres toques y ábrelo como cualquier app."), T("Help","Aide","Ayuda"))
    b = f'''<section style="padding-top:16px"><div class="wrap split"><div class="copy">
<h2 style="font-size:22px">iPhone</h2>{ol(ios)}<h2 style="font-size:22px;margin-top:44px">Android</h2>{ol(andr)}</div>
<div class="phones reveal" style="grid-template-columns:repeat(2,minmax(0,1fr));max-width:520px">{phone("login",lang,t(T("Sweep log-in screen on a phone","Écran de connexion Sweep sur téléphone","Pantalla de inicio de Sweep en el teléfono")))}{phone("overview",lang,t(T("Sweep overview on a phone","Aperçu Sweep sur téléphone","Resumen de Sweep en el teléfono")))}</div></div></section>'''
    ld = jsonld({"@context":"https://schema.org","@type":"HowTo","name":t(T("Install Sweep on iPhone","Installer Sweep sur iPhone","Instalar Sweep en iPhone")),"step":[{"@type":"HowToStep","position":i+1,"text":re.sub("<[^>]+>","",t(s))} for i,s in enumerate(ios)]})
    return (t(T("Install the Sweep app on iPhone and Android","Installer l’app Sweep sur iPhone et Android","Instalar la app Sweep en iPhone y Android")),
            t(T("Add Sweep to your iPhone or Android home screen from Safari or Chrome. Full screen, fast, no App Store needed.","Ajoute Sweep à l’écran d’accueil de ton iPhone ou Android depuis Safari ou Chrome. Plein écran, rapide, sans App Store.","Añade Sweep a la pantalla de inicio de tu iPhone o Android desde Safari o Chrome. Pantalla completa, rápido, sin App Store.")),
            hero + b + final_cta(lang, t), ld)

def page_security(lang, t):
    hero = page_hero(t, T("Your trading history, safe and yours.","Ton historique de trading, en sécurité et à toi.","Tu historial de trading, seguro y tuyo."),
        T("What Sweep stores, how it’s protected, and how to take it with you or delete it. In plain words.","Ce que Sweep conserve, comment c’est protégé, et comment l’emporter ou le supprimer. En mots simples.","Qué guarda Sweep, cómo se protege y cómo llevártelo o eliminarlo. En palabras simples."),
        T("Security and privacy","Sécurité et confidentialité","Seguridad y privacidad"))
    g = grid(t, [("archive",T("Lose an account, keep your history","Perds un compte, garde ton historique","Pierdes una cuenta, conservas tu historial"),T("Closing or failing a prop account never deletes your history. Export everything in one click, anytime.","Fermer ou échouer un compte prop ne supprime jamais ton historique. Exporte tout en un clic, à tout moment.","Cerrar o fallar una cuenta prop nunca borra tu historial. Exporta todo en un clic, cuando quieras.")),
        ("lock",T("Payments by Stripe","Paiements par Stripe","Pagos con Stripe"),T("Payments are processed by Stripe. Sweep never sees or stores your card number.","Les paiements sont traités par Stripe. Sweep ne voit ni ne stocke jamais ton numéro de carte.","Los pagos los procesa Stripe. Sweep nunca ve ni guarda el número de tu tarjeta.")),
        ("eye",T("Only you see your data","Toi seul vois tes données","Solo tú ves tus datos"),T("Each trader’s data is separate. The admin page shows usernames and usage, never trades or notes.","Les données de chaque trader sont séparées. La page admin montre les noms d’utilisateur et l’utilisation, jamais les trades ni les notes.","Los datos de cada trader están separados. La página de admin muestra usuarios y uso, nunca operaciones ni notas.")),
        ("key",T("Passwords are never readable","Mots de passe jamais lisibles","Contraseñas nunca legibles"),T("Stored only as a secure hash. Resets use a one-time link valid for one hour.","Conservés uniquement sous forme de hachage sécurisé. Les réinitialisations utilisent un lien unique valide une heure.","Se guardan solo como hash seguro. Los restablecimientos usan un enlace único válido una hora.")),
        ("shield",T("Protected sign-in","Connexion protégée","Acceso protegido"),T("HTTPS only, strict security headers, limits on log-in, sign-up and reset attempts, and anti-bot checks.","HTTPS seulement, en-têtes de sécurité stricts, limites de tentatives de connexion, d’inscription et de réinitialisation, et protection anti-robots.","Solo HTTPS, cabeceras de seguridad estrictas, límites de intentos de acceso, registro y restablecimiento, y protección antibots.")),
        ("image",T("Private screenshots","Captures privées","Capturas privadas"),T("Images you attach to trades are stored privately for your account only.","Les images jointes à tes trades sont conservées en privé, pour ton compte seulement.","Las imágenes que adjuntas se guardan en privado, solo para tu cuenta.")),
        ("layers",T("Social is opt-in","Le social est opt-in","Lo social es opcional"),T("No social feature is active without your consent. Others only ever see your username, rank and consistency, never your P&L, amounts, trades or accounts.","Aucune fonction sociale n’est active sans ton accord. Les autres ne voient que ton pseudo, ton rang et ta régularité, jamais ton P&L, tes montants, tes trades ou tes comptes.","Ninguna función social está activa sin tu consentimiento. Los demás solo ven tu usuario, tu rango y tu constancia, nunca tu P&L, importes, operaciones ni cuentas.")),
        ("download",T("Export everything","Exporte tout","Exporta todo"),T("One click gives you a ZIP file: a re-importable backup, CSV spreadsheets (trades, accounts, payouts, expenses, journal) and all your screenshots.","Un clic te donne un fichier ZIP : sauvegarde réimportable, tableurs CSV (trades, comptes, payouts, dépenses, journal) et toutes tes captures.","Un clic te da un archivo ZIP: copia reimportable, hojas CSV (operaciones, cuentas, payouts, gastos, diario) y todas tus capturas.")),
        ("trash",T("Delete instantly","Supprime instantanément","Elimina al instante"),T("Self-serve deletion in Settings removes everything, screenshots included, right away. Your password is required.","Réglages → Supprimer mon compte efface tout, captures comprises, tout de suite. Ton mot de passe est requis.","Ajustes → Eliminar mi cuenta lo borra todo, capturas incluidas, al instante. Se requiere tu contraseña."))])
    rows = [(T("Account","Compte","Cuenta"),T("Username, email, password hash, language, date you accepted the terms","Nom d’utilisateur, courriel, hachage du mot de passe, langue, date d’acceptation des conditions","Usuario, correo, hash de contraseña, idioma, fecha de aceptación de los términos")),
            (T("What you enter","Ce que tu saisis","Lo que introduces"),T("Accounts, trades, journals, payouts, expenses, settings and screenshots","Comptes, trades, journaux, payouts, dépenses, réglages et captures","Cuentas, operaciones, diarios, payouts, gastos, ajustes y capturas")),
            (T("Technical","Technique","Técnico"),T("IP addresses kept up to 24 hours, only to limit sign-in attempts","Adresses IP gardées jusqu’à 24 heures, seulement pour limiter les tentatives de connexion","Direcciones IP guardadas hasta 24 horas, solo para limitar intentos de acceso")),
            (T("On your device","Sur ton appareil","En tu dispositivo"),T("A session cookie (30 days), interface preferences (theme, language, filters, last account) and, if you came from a campaign link, a sweep_utm cookie with its campaign tags (30 days)","Un témoin de session (30 jours), tes préférences (thème, langue, filtres, dernier compte) et, si tu arrives d’un lien de campagne, un témoin sweep_utm avec ses étiquettes (30 jours)","Una cookie de sesión (30 días), preferencias (tema, idioma, filtros, última cuenta) y, si llegas desde un enlace de campaña, una cookie sweep_utm con sus etiquetas (30 días)")),
            (T("Where","Où","Dónde"),T("Sweep’s server at HostArmada. The database sits outside the public web folder","Le serveur de Sweep chez HostArmada. La base de données est hors du dossier web public","El servidor de Sweep en HostArmada. La base de datos está fuera de la carpeta web pública")),
            (T("Third parties","Tiers","Terceros"),T("Stripe for payments (Sweep never sees your card number); Discord, only if you connect your account; Google (Gemini API, Google Search) when you use an AI feature and to prepare economic reports; Google Fonts for the app’s typeface. No analytics, no ads, no trackers, no data sold. Emails are sent from Sweep’s own server","Stripe pour les paiements (Sweep ne voit jamais ton numéro de carte); Discord, seulement si tu connectes ton compte; Google (API Gemini, Recherche Google) quand tu utilises une fonction IA et pour préparer les rapports économiques; Google Fonts pour la police de l’app. Aucune analytique, aucune pub, aucun traqueur, aucune donnée vendue. Les courriels partent du serveur de Sweep","Stripe para los pagos (Sweep nunca ve tu número de tarjeta); Discord, solo si conectas tu cuenta; Google (API Gemini, Búsqueda de Google) cuando usas una función de IA y para preparar los informes económicos; Google Fonts para la tipografía de la app. Sin analítica, anuncios, rastreadores ni venta de datos. Los correos salen del servidor de Sweep")),
            (T("Visible to others","Visible par les autres","Visible para otros"),T("Only if you join leagues, crews or a buddy: your username, rank and consistency. A buddy also sees your rings and streak. Never P&L, amounts, trades or accounts","Seulement si tu rejoins une ligue, un crew ou un buddy : ton pseudo, ton rang et ta régularité. Un buddy voit aussi tes anneaux et ton streak. Jamais de P&L, de montants, de trades ni de comptes","Solo si te unes a ligas, crews o un buddy: tu usuario, tu rango y tu constancia. Un buddy también ve tus anillos y tu racha. Nunca P&L, importes, operaciones ni cuentas")),
            (T("Sweep AI","Sweep AI","Sweep AI"),T("Nothing is sent until you tap an AI action, then only what it needs. Ask Sweep conversations stay in your browser for the session. Deleting your account deletes its AI history","Rien n’est envoyé avant que tu touches une action IA, puis seulement le nécessaire. Les discussions Ask Sweep restent dans ton navigateur pour la session. Supprimer ton compte supprime son historique IA","No se envía nada hasta que tocas una acción de IA, y luego solo lo necesario. Las conversaciones de Ask Sweep quedan en tu navegador durante la sesión. Eliminar tu cuenta elimina su historial de IA"))]
    tbl = '<table class="tbl"><tbody>' + "".join(f"<tr><th>{t(a)}</th><td>{t(c)}</td></tr>" for a,c in rows) + "</tbody></table>"
    b = f'<section style="padding-top:16px"><div class="wrap">{g}</div></section><section class="rule"><div class="wrap narrow"><div class="head"><h2>{t(T("What we store","Ce que nous conservons","Qué guardamos"))}</h2></div>{tbl}<p class="meta" style="margin-top:28px"><a href="{href(lang,"privacy.html")}">{t(T("Read the full privacy policy","Lire la politique de confidentialité complète","Leer la política de privacidad completa"))}</a></p></div></section>'
    return (t(T("Security and privacy · Sweep","Sécurité et confidentialité · Sweep","Seguridad y privacidad · Sweep")),
            t(T("How Sweep protects your trading data: private by default, hashed passwords, JSON export, instant account deletion, no ads or trackers.","Comment Sweep protège tes données de trading : privé par défaut, mots de passe hachés, export JSON, suppression immédiate, ni pubs ni traqueurs.","Cómo Sweep protege tus datos de trading: privado por defecto, contraseñas con hash, exportación JSON, eliminación inmediata, sin anuncios ni rastreadores.")),
            hero + b + final_cta(lang, t), "")

def page_pricing(lang, t):
    from core import ul
    hero = f'<div class="page-hero" style="text-align:center"><div class="wrap"><span class="kick">{t(T("Pricing","Tarifs","Precios"))}</span><h1 class="wu" style="margin:0 auto">{words(t(T("Free while we build it together.","Gratuit pendant qu’on le bâtit ensemble.","Gratis mientras lo construimos juntos.")))}</h1><p class="lead" style="margin-left:auto;margin-right:auto">{t(T("Every feature, free during early access. Join now and keep VIP pricing when paid plans arrive.","Toutes les fonctionnalités, gratuites pendant l’accès anticipé. Inscris-toi maintenant et garde un prix VIP quand les forfaits payants arriveront.","Todas las funciones, gratis durante el acceso anticipado. Únete ahora y conserva el precio VIP cuando lleguen los planes de pago."))}</p></div></div>'
    feats = [T("Unlimited trades and accounts","Trades et comptes illimités","Operaciones y cuentas ilimitadas"),T("Trade ticket with live risk and daily risk budget","Ticket avec risque en direct et budget de risque","Ticket con riesgo en vivo y presupuesto de riesgo"),
             T("Automatic rule checks and discipline checklist","Vérification automatique des règles et checklist de discipline","Revisión automática de reglas y checklist de disciplina"),T("Guided trade review and screenshots","Révision guidée et captures","Revisión guiada y capturas"),
             T("Insights, performance score and deep dives","Analyses, score de performance et analyses poussées","Análisis, puntuación de rendimiento y análisis a fondo"),T("P&L calendar, daily journal and weekly review","Calendrier P&L, journal quotidien et révision hebdo","Calendario de P&L, diario y revisión semanal"),
             T("Economic calendar linked to your trades","Calendrier économique lié à tes trades","Calendario económico vinculado a tus operaciones"),T("Prop firm rules, trade copier, payouts and expenses","Règles des firmes, copieur, payouts et dépenses","Reglas de firmas, copiador, payouts y gastos"),
             T("Tradovate CSV import and JSON export","Import CSV Tradovate et export JSON","Importación CSV de Tradovate y exportación JSON"),
             T("✦ Sweep AI and Ask Sweep, included with a daily limit","✦ Sweep AI et Ask Sweep, inclus avec une limite quotidienne","✦ Sweep AI y Ask Sweep, incluidos con un límite diario"),
             T("AI economic recaps and market reports","Récaps économiques et rapports de marché par IA","Resúmenes económicos e informes de mercado con IA")]
    vip = [T("A VIP discount on paid plans, for members who joined during early access","Un rabais VIP sur les forfaits payants pour les membres de l’accès anticipé","Un descuento VIP en los planes de pago para quienes se unieron en el acceso anticipado"),
           T("Pricing announced before anything changes","Les prix annoncés avant tout changement","Precios anunciados antes de cualquier cambio"),
           T("Nothing charged without your consent","Rien facturé sans ton accord","Nada se cobra sin tu consentimiento"),
           T("Your data stays yours: export or delete anytime","Tes données restent à toi : exporte ou supprime en tout temps","Tus datos siguen siendo tuyos: exporta o elimina cuando quieras")]
    b = f'''<section style="padding-top:8px"><div class="wrap"><div class="plans">
<div class="plan main reveal"><h2 style="font-size:20px">{t(T("Early access","Accès anticipé","Acceso anticipado"))}</h2><div class="price"><span class="num">$0</span><span class="muted">{t(T("now","maintenant","ahora"))}</span></div>
<p class="muted" style="font-size:15px">{t(T("Everything in Sweep. No credit card.","Tout Sweep. Sans carte de crédit.","Todo Sweep. Sin tarjeta."))}</p>{ul(t,feats)}<a class="btn btn-primary btn-lg" href="{SIGNUP}">{t(CREATE_FREE)}</a></div>
<div class="plan reveal"><h2 style="font-size:20px">{t(T("At launch","Au lancement","En el lanzamiento"))}</h2><div class="price"><span class="num">VIP</span><span class="muted">{t(T("for early members","pour les premiers membres","para los primeros miembros"))}</span></div>
<p class="muted" style="font-size:15px">{t(T("When Sweep officially launches with paid plans.","Quand Sweep sera officiellement lancé avec des forfaits payants.","Cuando Sweep se lance oficialmente con planes de pago."))}</p>{ul(t,vip)}<a class="btn btn-line btn-lg" href="{SIGNUP}">{t(T("Claim VIP access","Obtenir l’accès VIP","Obtener acceso VIP"))}</a></div>
</div></div></section>'''
    b += f'<section class="rule"><div class="wrap narrow"><div class="head"><h2>{t(T("Pricing questions","Questions sur les tarifs","Preguntas sobre precios"))}</h2></div>{"".join(faq_item(t,q,a) for q,a in FAQ[3][1])}</div></section>'
    return (t(T("Pricing · Free early access with VIP launch pricing · Sweep","Tarifs · Accès anticipé gratuit et prix VIP au lancement · Sweep","Precios · Acceso anticipado gratis y precio VIP al lanzar · Sweep")),
            t(T("Sweep is free during early access with every feature included. Members who join now get a VIP discount when paid plans launch.","Sweep est gratuit pendant l’accès anticipé, avec toutes les fonctionnalités. Les membres inscrits maintenant auront un rabais VIP au lancement des forfaits payants.","Sweep es gratis durante el acceso anticipado, con todas las funciones. Quienes se unan ahora tendrán un descuento VIP cuando lleguen los planes de pago.")),
            hero + b + final_cta(lang, t), "")

def page_about(lang, t):
    story = T("""<p><b>Sweep started as one trader’s journal.</b> It was built for a small community of futures traders who were tired of spreadsheets, scattered screenshots, and firm dashboards that disappeared with every prop account.</p>
<p>The name comes from market structure. A sweep takes the liquidity below a level before price moves higher. Trading works the same way: the losing days, the broken rules and the lessons are the low that gets swept. What you do with them is the move that follows.</p>
<p>Sweep is built in Quebec by Sweep Inc. It exists to make that next move easier: one place for every trade, rule, account and payout, an honest look at what works, and a history you keep no matter what happens to an account.</p>""",
"""<p><b>Sweep a commencé comme le journal d’un trader.</b> Il a été conçu pour une petite communauté de traders de futures, tannés des tableurs, des captures éparpillées et des tableaux de bord qui disparaissaient avec chaque compte prop.</p>
<p>Le nom vient de la structure de marché. Un sweep va chercher la liquidité sous un niveau avant que le prix monte. Le trading fonctionne pareil : les journées perdantes, les règles brisées et les leçons sont le creux qui se fait balayer. Ce que tu en fais, c’est le mouvement qui suit.</p>
<p>Sweep est conçu au Québec par Sweep Inc. Il existe pour rendre ce prochain mouvement plus facile : un seul endroit pour chaque trade, règle, compte et payout, un regard honnête sur ce qui marche, et un historique que tu gardes peu importe ce qui arrive à un compte.</p>""",
"""<p><b>Sweep empezó como el diario de un trader.</b> Se creó para una pequeña comunidad de traders de futuros, cansados de hojas de cálculo, capturas dispersas y paneles que desaparecían con cada cuenta prop.</p>
<p>El nombre viene de la estructura de mercado. Un sweep toma la liquidez bajo un nivel antes de que el precio suba. El trading funciona igual: los días perdedores, las reglas rotas y las lecciones son el mínimo que se barre. Lo que haces con ellos es el movimiento que sigue.</p>
<p>Sweep se crea en Quebec por Sweep Inc. Existe para facilitar ese siguiente movimiento: un solo lugar para cada operación, regla, cuenta y payout, una mirada honesta a lo que funciona y un historial que conservas pase lo que pase con una cuenta.</p>""")
    hero = page_hero(t, T("About Sweep","À propos de Sweep","Acerca de Sweep"), T("Why Sweep exists, and what it will never do.","Pourquoi Sweep existe, et ce qu’il ne fera jamais.","Por qué existe Sweep y lo que nunca hará."), T("About","À propos","Acerca de"))
    ident = T("<p><b>Sweep is a free trading journal built for futures and prop firm traders.</b> It was born in a Discord community of futures traders, tested for months by trader friends before it had a name, and launched publicly on October 1, 2026.</p><p><b>Our mission:</b> give every trader the system to become consistently profitable: build the habits, find the edge, get the payouts, track the expenses, and never lose a trading history again.</p>",
              "<p><b>Sweep est un journal de trading gratuit conçu pour les traders de futures et de prop firms.</b> Il est né dans une communauté Discord de traders de futures, a été testé pendant des mois par des amis traders avant même d’avoir un nom, et a été lancé publiquement le 1er octobre 2026.</p><p><b>Notre mission :</b> donner à chaque trader le système pour devenir régulièrement rentable : bâtir les habitudes, trouver son edge, obtenir ses payouts, suivre ses dépenses, et ne plus jamais perdre son historique.</p>",
              "<p><b>Sweep es un diario de trading gratuito creado para traders de futuros y de prop firms.</b> Nació en una comunidad de Discord de traders de futuros, lo probaron durante meses amigos traders antes de tener nombre y se lanzó públicamente el 1 de octubre de 2026.</p><p><b>Nuestra misión:</b> dar a cada trader el sistema para ser rentable de forma constante: crear los hábitos, encontrar su ventaja, cobrar sus payouts, seguir sus gastos y no volver a perder su historial.</p>")
    b = f'<section style="padding-top:16px"><div class="wrap split"><div class="prose" style="font-size:17px;color:var(--muted)">{(t(ident)+t(story)).replace("<b>","<b style=\"color:var(--text);font-weight:500\">")}</div><div class="reveal">{slot("v6-01-today-d.webp","desktop",t(T("Sweep, the Today screen, sample data","Sweep, l’écran Aujourd’hui, données d’exemple","Sweep, la pantalla Hoy, datos de ejemplo")),t)}</div></div></section>'
    b += f'<section class="rule"><div class="wrap narrow"><h2>{t(T("The company","L’entreprise","La empresa"))}</h2><p class="lead">Sweep Inc.<br>3980 Blvd St-Elzear O, Laval (Québec) H7P 0M2, Canada<br><a href="mailto:{EMAIL}">{EMAIL}</a></p></div></section>'
    b += '<section class="rule"><div class="wrap">' + f'<div class="head"><h2>{t(T("What we believe","Ce en quoi on croit","En qué creemos"))}</h2></div>' + grid(t,[
        ("archive",T("Your data stays yours","Tes données restent à toi","Tus datos son tuyos"),T("Private, exportable, deletable, never sold.","Privées, exportables, supprimables, jamais vendues.","Privados, exportables, eliminables, nunca vendidos.")),
        ("check",T("Honest numbers","Des chiffres honnêtes","Números honestos"),T("The bad days count. A warning never hides a broken rule.","Les mauvaises journées comptent. Un avertissement ne cache jamais une règle brisée.","Los días malos cuentan. Un aviso nunca oculta una regla rota.")),
        ("bolt",T("No signals, no hype","Ni signaux ni hype","Sin señales ni exageraciones"),T("Sweep shows your data. The decisions stay yours.","Sweep montre tes données. Les décisions restent les tiennes.","Sweep muestra tus datos. Las decisiones son tuyas."))]) + '</div></section>'
    return (t(T("About Sweep","À propos de Sweep","Acerca de Sweep")), t(T("Sweep is a trading journal built in Quebec by a futures trader, for futures and prop traders.","Sweep est un journal de trading conçu au Québec par un trader de futures, pour les traders de futures et prop.","Sweep es un diario de trading creado en Quebec por un trader de futuros, para traders de futuros y prop.")), hero + b + final_cta(lang, t), "")

def page_contact(lang, t):
    hero = page_hero(t, T("Talk to us.","Écris-nous.","Escríbenos."), T("Questions, feedback, a bug or a feature you need. A real person reads every message.","Questions, commentaires, un bug ou une fonctionnalité qui te manque. Une vraie personne lit chaque message.","Preguntas, comentarios, un error o una función que necesitas. Una persona real lee cada mensaje."), T("Contact","Contact","Contacto"))
    b = f'''<section style="padding-top:16px"><div class="wrap"><div class="grid g2">
<div>{ico(I["globe"])}<h3>{t(T("Email","Courriel","Correo"))}</h3><p>{t(T("Support, accounts, privacy requests and feedback.","Soutien, comptes, demandes de confidentialité et commentaires.","Soporte, cuentas, solicitudes de privacidad y comentarios."))}</p><div class="cta-row"><a class="btn btn-line" href="mailto:{EMAIL}">{EMAIL}</a></div></div>
<div>{ico(I["key"])}<h3>{t(T("Account help","Aide pour ton compte","Ayuda con tu cuenta"))}</h3><p>{t(T("Forgot your password? Use “Forgot password?” on the log-in screen to get a reset link by email.","Mot de passe oublié? Utilise « Mot de passe oublié? » sur l’écran de connexion pour recevoir un lien par courriel.","¿Olvidaste tu contraseña? Usa «¿Olvidaste tu contraseña?» en la pantalla de inicio para recibir un enlace por correo."))}</p><div class="cta-row"><a class="btn btn-line" href="{APP}">{t(LOGIN)}</a></div></div>
</div>
<div class="follow"><div><h3>{t(T("Follow Sweep","Suis Sweep","Sigue a Sweep"))}</h3><p class="muted">{t(T("Tips, product updates and the first 100, on Instagram, TikTok and Facebook.","Conseils, nouveautés et les 100 premiers, sur Instagram, TikTok et Facebook.","Consejos, novedades y los primeros 100, en Instagram, TikTok y Facebook."))}</p></div>{social_links("social big")}</div>
<p class="meta" style="margin-top:28px">Sweep Inc. · 3980 Blvd St-Elzear O, Laval (Québec) H7P 0M2, Canada</p></div></section>'''
    return (t(T("Contact Sweep","Contacter Sweep","Contactar con Sweep")), t(T(f"Contact the Sweep team at {EMAIL} for support, privacy requests and feedback.",f"Joins l’équipe Sweep à {EMAIL} pour du soutien, des demandes de confidentialité et des commentaires.",f"Contacta al equipo de Sweep en {EMAIL} para soporte, privacidad y comentarios.")), hero + b, "")

def page_changelog(lang, t):
    hero = page_hero(t, T("What’s new in Sweep.","Nouveautés dans Sweep.","Novedades en Sweep."), T("Every release, in plain words.","Chaque version, en mots simples.","Cada versión, en palabras simples."), T("Changelog","Journal des changements","Registro de cambios"))
    items = [T("Trade ticket with live risk, R:R and daily risk budget","Ticket avec risque en direct, R:R et budget de risque quotidien","Ticket con riesgo en vivo, R:R y presupuesto de riesgo diario"),
             T("Automatic rule checks and an editable 13-question discipline checklist","Vérification automatique des règles et checklist de discipline de 13 questions modifiable","Revisión automática de reglas y checklist editable de 13 preguntas"),
             T("Guided 4-step trade review with chart, psychology, notes and screenshots","Révision guidée en 4 étapes avec graphique, psychologie, notes et captures","Revisión guiada en 4 pasos con gráfico, psicología, notas y capturas"),
             T("Insights with a 6-measure performance score, patterns to watch and deep dives","Analyses avec score de performance à 6 mesures, tendances à surveiller et analyses poussées","Análisis con puntuación de 6 medidas, patrones a vigilar y análisis a fondo"),
             T("P&L calendar, daily journal and weekly review","Calendrier P&L, journal quotidien et révision hebdomadaire","Calendario de P&L, diario y revisión semanal"),
             T("U.S. economic calendar linked to every trade","Calendrier économique américain lié à chaque trade","Calendario económico de EE. UU. vinculado a cada operación"),
             T("Prop accounts with firm rules, trade copier, payouts and expenses","Comptes prop avec règles des firmes, copieur, payouts et dépenses","Cuentas prop con reglas, copiador, payouts y gastos"),
             T("Tradovate CSV import, JSON export, instant account deletion","Import CSV Tradovate, export JSON, suppression de compte immédiate","Importación CSV de Tradovate, exportación JSON, eliminación inmediata"),
             T("English, French and Spanish; dark and light; installable on your phone","Anglais, français et espagnol; foncé et clair; installable sur ton téléphone","Inglés, francés y español; oscuro y claro; instalable en tu teléfono")]
    from core import ul
    items2 = [T("<b>Sweep AI:</b> log trades in plain words or from a screenshot, scan receipts, weekly review, day debrief, trade feedback and setup suggestions","<b>Sweep AI :</b> saisie en mots simples ou par capture, scan de reçus, bilan hebdo, débrief de la journée, avis sur les trades et suggestions de setup","<b>Sweep AI:</b> registro con tus palabras o por captura, escaneo de recibos, revisión semanal, resumen del día, opinión sobre operaciones y sugerencias de setup"),
              T("<b>Ask Sweep,</b> your trading assistant for your stats, today’s news and the app","<b>Ask Sweep,</b> ton assistant de trading pour tes stats, les nouvelles du jour et l’app","<b>Ask Sweep,</b> tu asistente de trading para tus estadísticas, las noticias de hoy y la app"),
              T("<b>AI economic calendar:</b> numbers filled in, flash recap about a minute after U.S. releases, full market report at about 30 minutes","<b>Calendrier économique IA :</b> chiffres remplis, récap éclair environ une minute après les annonces, rapport complet vers 30 minutes","<b>Calendario económico con IA:</b> cifras completadas, resumen flash aproximadamente un minuto después, informe completo hacia los 30 minutos"),
              T("New sign-in and welcome flow, password reset by email","Nouvelle connexion et accueil, réinitialisation du mot de passe par courriel","Nuevo inicio de sesión y bienvenida, restablecimiento de contraseña por correo"),
              T("2-step trade entry, guided trade review, iOS-style filters and sheets","Saisie en 2 étapes, révision guidée, filtres et fenêtres style iOS","Registro en 2 pasos, revisión guiada, filtros y paneles estilo iOS")]
    items4 = [T("<b>Real CME charts</b> for 14 contracts: tap a candle to log, drag your stop and target, result in R","<b>Vrais graphiques CME</b> pour 14 contrats : touche une bougie pour journaliser, glisse ton stop et ton objectif, résultat en R","<b>Gráficos reales de CME</b> para 14 contratos: toca una vela para registrar, arrastra stop y objetivo, resultado en R"),
              T("<b>Sweep your day:</b> three rings, discipline streak and streak freezes","<b>Balaye ta journée :</b> trois anneaux, streak de discipline et gels de streak","<b>Barre tu día:</b> tres anillos, racha de disciplina y congelaciones"),
              T("<b>Gamification:</b> XP, 7 ranks, 35+ badges, path, weekly missions, bosses, weekly review and chest, Edge Reveal, Wrapped, seasons","<b>Gamification :</b> XP, 7 rangs, 35+ badges, parcours, missions, boss, revue de la semaine et coffre, Edge Reveal, Wrapped, saisons","<b>Gamificación:</b> XP, 7 rangos, más de 35 insignias, recorrido, misiones, jefes, revisión semanal y cofre, Edge Reveal, Wrapped, temporadas"),
              T("<b>Social, opt-in:</b> leagues, crews, accountability buddy, Discord roles. Never your P&L","<b>Social, opt-in :</b> ligues, crews, accountability buddy, rôles Discord. Jamais ton P&L","<b>Social, opcional:</b> ligas, crews, accountability buddy, roles de Discord. Nunca tu P&L"),
              T("<b>Prop firm presets</b> and a “ready for payout” meter","<b>Préréglages de prop firms</b> et compteur « prêt pour le payout »","<b>Preajustes de prop firms</b> e indicador «listo para el payout»"),
              T("<b>Free forever,</b> with Pro included for your first 60 days; full ZIP export; feedback loop","<b>Gratuit pour toujours,</b> avec Pro offert pendant tes 60 premiers jours; export ZIP complet; boucle de feedback","<b>Gratis para siempre,</b> con Pro incluido tus primeros 60 días; exportación ZIP completa; ciclo de feedback")]
    items3 = [T("<b>Plans:</b> Free, Pro and Elite","<b>Forfaits :</b> Free, Pro et Elite","<b>Planes:</b> Free, Pro y Elite"),
              T("<b>Share cards</b> for payouts, weekly recaps, net after fees, days and trades, amounts optional","<b>Cartes à partager</b> pour les payouts, récaps hebdo, net après frais, journées et trades, montants optionnels","<b>Tarjetas para compartir</b> de payouts, resúmenes semanales, neto tras comisiones, días y operaciones, importes opcionales"),
              T("<b>Sync across devices</b> with pull to refresh on phones","<b>Synchronisation entre appareils</b> avec « tirer pour actualiser » sur téléphone","<b>Sincronización entre dispositivos</b> con deslizar para actualizar en el móvil"),
              T("Redesigned phone screens: cards for accounts, payouts and expenses, a swipeable journal day strip and calendar","Écrans de téléphone repensés : cartes pour les comptes, payouts et dépenses, bande de jours et calendrier à balayer","Pantallas del móvil rediseñadas: tarjetas para cuentas, payouts y gastos, franja de días y calendario deslizables")]
    b = f'''<section style="padding-top:16px"><div class="wrap"><div class="log"><article><time datetime="{TODAY2}">{t(T("October 3, 2026","3 octobre 2026","3 de octubre de 2026"))}</time>
<h2>{t(T("Sweep has a new look","Sweep fait peau neuve","Sweep se renueva"))}</h2>{ul(t,items4)}</article><article><time datetime="2026-10-02">{t(T("October 2, 2026","2 octobre 2026","2 de octubre de 2026"))}</time>
<h2>{t(T("Plans, share cards and sync","Forfaits, cartes à partager et synchronisation","Planes, tarjetas para compartir y sincronización"))}</h2>{ul(t,items3)}</article><article><time datetime="2026-10-02">{t(T("October 2026","Octobre 2026","Octubre de 2026"))}</time>
<h2>{t(T("Sweep AI, Ask Sweep and AI market reports","Sweep AI, Ask Sweep et rapports de marché IA","Sweep AI, Ask Sweep e informes de mercado con IA"))}</h2>{ul(t,items2)}</article><article><time datetime="{TODAY}">{t(T("October 1, 2026","1er octobre 2026","1 de octubre de 2026"))}</time>
<h2>{t(T("Early access opens","Ouverture de l’accès anticipé","Se abre el acceso anticipado"))}</h2><p class="muted">{t(T("Sweep opens to every futures trader, free during early access, with a founding price reserved for early members.","Sweep ouvre ses portes à tous les traders de futures, gratuitement, avec un prix fondateur réservé aux premiers membres.","Sweep se abre a todos los traders de futuros, gratis, con un precio fundador reservado a los primeros miembros."))}</p>{ul(t,items)}</article></div></div></section>'''
    return (t(T("What’s new · Sweep changelog","Nouveautés · Journal des changements Sweep","Novedades · Registro de cambios de Sweep")), t(T("What’s new in Sweep: real CME charts, the daily rings, gamification, social features, prop firm presets and plans.","Nouveautés de Sweep : vrais graphiques CME, anneaux du jour, gamification, fonctions sociales, préréglages de prop firms et forfaits.","Novedades de Sweep: gráficos reales de CME, anillos diarios, gamificación, funciones sociales, preajustes de prop firms y planes.")), hero + b + final_cta(lang, t), "")

def page_404(lang, t):
    b = f'''<section class="final" style="padding-top:clamp(96px,14vw,180px)"><div class="wrap"><span class="mark" aria-hidden="true">{ANIM_MARK}</span>
<h1>{t(T("This page got swept.","Cette page s’est fait balayer.","Esta página fue barrida."))}</h1><p class="lead">{t(T("It doesn’t exist or it moved. The way back is up.","Elle n’existe pas ou a été déplacée. Le chemin du retour, c’est vers le haut.","No existe o se movió. El camino de vuelta es hacia arriba."))}</p>
<div class="cta-row"><a class="btn btn-primary btn-lg" href="{href(lang,'index.html')}">{t(T("Back to home","Retour à l’accueil","Volver al inicio"))}</a></div></div></section>'''
    return ("404 · Sweep", t(T("This page doesn’t exist or it moved. Head back to the Sweep home page.","Cette page n’existe pas ou a été déplacée. Retourne à l’accueil de Sweep.","Esta página no existe o se movió. Vuelve al inicio de Sweep.")), b, "")
