from core import *

TPL = {"en":("trading-plan","daily-journal","discipline-checklist"),"fr":("plan-de-trading","journal-quotidien","checklist-discipline"),"es":("plan-de-trading","diario-de-trading","checklist-disciplina")}
ITEMS = [
 ("doc", T("Trading plan","Plan de trading","Plan de trading"), T("Markets, sessions, A and B setups, entry and exit rules, risk per trade, daily limits and when you stop. One page.","Marchés, sessions, setups A et B, règles d’entrée et de sortie, risque par trade, limites du jour et quand tu arrêtes. Une page.","Mercados, sesiones, setups A y B, reglas de entrada y salida, riesgo por operación, límites diarios y cuándo paras. Una página.")),
 ("calendar", T("Daily journal","Journal quotidien","Diario"), T("Bias, levels and scenarios before the open, a trade log during the session, and four review questions after the close.","Biais, niveaux et scénarios avant l’ouverture, un registre de trades pendant la séance, et quatre questions de revue après la clôture.","Sesgo, niveles y escenarios antes de la apertura, un registro de operaciones durante la sesión y cuatro preguntas de revisión al cierre.")),
 ("check", T("Discipline checklist","Checklist de discipline","Checklist de disciplina"), T("Eight yes-or-no questions before every trade, and a weekly review on the same page.","Huit questions oui ou non avant chaque trade, et une revue de la semaine sur la même page.","Ocho preguntas de sí o no antes de cada operación y una revisión semanal en la misma página.")),
]

def page_templates(lang, t):
    hero = page_hero(t, T("Free trading templates.","Modèles de trading gratuits.","Plantillas de trading gratuitas."),
        T("Print them, fill them in, keep them next to your screen. No email needed.","Imprime-les, remplis-les, garde-les à côté de ton écran. Sans courriel.","Imprímelas, rellénalas y tenlas junto a tu pantalla. Sin email."), T("Templates","Modèles","Plantillas"))
    fl = TPL[lang]
    cards = "".join(f'<a class="tool-card" href="/templates/{lang}/{fl[i]}.pdf" download data-track="template_{TPL["en"][i]}">{ico(I[ic])}<h2>{t(n)}</h2><p>{t(d)}</p><span class="go">{t(T("Download the PDF","Télécharger le PDF","Descargar el PDF"))} ↓</span></a>' for i,(ic,n,d) in enumerate(ITEMS))
    b = (f'<section style="padding-top:8px"><div class="wrap"><div class="tool-grid">{cards}</div></div></section>'
         f'<section class="rule"><div class="wrap narrow"><div class="head"><h2>{t(T("Paper is a start. Sweep does the rest.","Le papier, c’est un début. Sweep fait le reste.","El papel es un comienzo. Sweep hace el resto."))}</h2>'
         f'<p class="lead">{t(T("Your checklist is on the same screen as every trade, your plan feeds the Plan ring, and your weekly review starts from your real numbers.","Ta checklist est sur le même écran que chaque trade, ton plan nourrit l’anneau Plan, et ta revue de la semaine part de tes vrais chiffres.","Tu checklist está en la misma pantalla que cada operación, tu plan alimenta el anillo Plan y tu revisión semanal parte de tus números reales."))}</p></div>'
         f'<p class="firm-others"><span>{t(T("Read next","À lire","Para leer"))}</span><a href="{href(lang,"trading-journal-routine.html")}">{t(T("A daily journaling routine","Une routine de journal quotidienne","Una rutina diaria de diario"))}</a><a href="{href(lang,"how-to-choose-a-trading-journal.html")}">{t(T("How to choose a trading journal","Bien choisir son journal de trading","Cómo elegir un diario de trading"))}</a></p></div></section>')
    return (t(T("Free trading plan, daily journal and checklist templates (PDF) · Sweep","Modèles gratuits : plan de trading, journal et checklist (PDF) · Sweep","Plantillas gratis: plan de trading, diario y checklist (PDF) · Sweep")),
            t(T("Download a printable trading plan, daily trading journal and discipline checklist for futures and prop firm traders. Free, no email.","Télécharge un plan de trading, un journal quotidien et une checklist de discipline à imprimer, pour traders de futures et de prop firms. Gratuit, sans courriel.","Descarga un plan de trading, un diario y un checklist de disciplina imprimibles para traders de futuros y de fondeo. Gratis, sin email.")),
            hero + b + final_cta(lang, t), "")

def _article(lang, t, h1, lead, kick, sections, related, title, desc):
    hero = page_hero(t, h1, lead, kick)
    body = "".join(f'<h2>{t(h)}</h2>' + "".join(f"<p>{t(p)}</p>" for p in ps) for h, ps in sections)
    rel = "".join(f'<a href="{href(lang,s)}">{t(n)}</a>' for s,n in related)
    b = f'<section style="padding-top:8px"><div class="wrap narrow"><article class="article">{body}</article><p class="firm-others" style="margin-top:36px"><span>{t(T("Related","Voir aussi","Ver también"))}</span>{rel}</p></div></section>'
    ld = jsonld({"@context":"https://schema.org","@type":"Article","headline":t(h1),"description":t(desc),"inLanguage":lang,"publisher":{"@id":f"https://{DOMAIN}/#org"},"datePublished":"2026-10-06","author":{"@type":"Organization","name":"Sweep"}})
    return (t(title), t(desc), hero + b + final_cta(lang, t), ld)

def page_choose(lang, t):
    S = [
     (T("1. It should match your platform’s numbers","1. Il doit afficher les chiffres de ta plateforme","1. Debe mostrar los números de tu plataforma"),
      [T("A journal you can’t trust is a journal you stop opening. Your net P&L should match your platform to the cent, fees included, and partial exits and adds should produce the same average price your platform shows.","Un journal en qui tu n’as pas confiance, tu arrêtes de l’ouvrir. Ton P&L net doit correspondre à ta plateforme au cent près, frais compris, et les sorties partielles et ajouts doivent donner le même prix moyen que ta plateforme.","Un diario en el que no confías es un diario que dejas de abrir. Tu P&L neto debe coincidir con tu plataforma al céntimo, comisiones incluidas, y las salidas parciales y añadidos deben dar el mismo precio medio."),
       T("Check how it handles commission per contract, slippage, and what happens when a number is off: can you correct it without breaking your statistics?","Vérifie comment il gère la commission par contrat, le glissement, et ce qui se passe quand un chiffre est faux : peux-tu le corriger sans fausser tes statistiques ?","Comprueba cómo trata la comisión por contrato, el deslizamiento y qué pasa cuando un número no cuadra: ¿puedes corregirlo sin alterar tus estadísticas?")]),
     (T("2. It should know prop firm rules","2. Il doit connaître les règles des prop firms","2. Debe conocer las reglas de las prop firms"),
      [T("If you trade evaluations and funded accounts, a generic journal leaves the hardest part to you: trailing drawdown, daily loss, consistency, minimum days and payout conditions. Look for rules per account, with presets you can edit, and a clear view of what’s missing before your next payout.","Si tu trades des évaluations et des comptes financés, un journal générique te laisse le plus difficile : drawdown suiveur, perte quotidienne, consistance, jours minimum et conditions de payout. Cherche des règles par compte, avec des préréglages modifiables, et une vue claire de ce qui manque avant ton prochain payout.","Si operas evaluaciones y cuentas fondeadas, un diario genérico te deja lo más difícil: drawdown dinámico, pérdida diaria, consistencia, días mínimos y condiciones de payout. Busca reglas por cuenta, con preajustes editables, y una vista clara de lo que falta antes del próximo payout."),
       T("Copy trading matters too: one decision on five accounts should count as one trade in your statistics, not five.","Le copy trading compte aussi : une décision sur cinq comptes doit compter comme un seul trade dans tes statistiques, pas cinq.","El copy trading también importa: una decisión en cinco cuentas debe contar como una sola operación, no cinco.")]),
     (T("3. Logging has to take seconds","3. Ajouter un trade doit prendre quelques secondes","3. Registrar debe llevar segundos"),
      [T("The best journal is the one you actually fill in. Importing a file, pasting a screenshot or typing a trade by hand should all be fast, and the discipline questions should sit on the same screen, while the trade is still fresh.","Le meilleur journal, c’est celui que tu remplis vraiment. Importer un fichier, coller une capture ou saisir un trade à la main doit être rapide, et les questions de discipline doivent être sur le même écran, pendant que le trade est encore frais.","El mejor diario es el que realmente rellenas. Importar un archivo, pegar una captura o escribir una operación debe ser rápido, y las preguntas de disciplina deben estar en la misma pantalla, con la operación aún fresca.")]),
     (T("4. It should reward process, not profit","4. Il doit récompenser le processus, pas le profit","4. Debe premiar el proceso, no el beneficio"),
      [T("A day’s P&L is partly luck. What you control is the plan before the open, following your rules, and the review after the close. A journal that measures and rewards those habits keeps you consistent on the days the market doesn’t cooperate.","Le P&L d’une journée dépend en partie du hasard. Ce que tu contrôles, c’est le plan avant l’ouverture, le respect de tes règles et la revue après la clôture. Un journal qui mesure et récompense ces habitudes te garde régulier les jours où le marché ne coopère pas.","El P&L de un día es en parte suerte. Lo que controlas es el plan antes de la apertura, seguir tus reglas y la revisión tras el cierre. Un diario que mide y premia esos hábitos te mantiene constante los días en que el mercado no ayuda.")]),
     (T("5. Your data stays yours","5. Tes données restent à toi","5. Tus datos siguen siendo tuyos"),
      [T("You should be able to export everything in a usable format and delete your account yourself. Social features, if any, should be opt-in and never show your P&L.","Tu dois pouvoir tout exporter dans un format utilisable et supprimer ton compte toi-même. Les fonctions sociales, s’il y en a, doivent être optionnelles et ne jamais montrer ton P&L.","Debes poder exportarlo todo en un formato útil y eliminar tu cuenta tú mismo. Las funciones sociales, si las hay, deben ser opcionales y no mostrar nunca tu P&L.")]),
     (T("A quick checklist","Une checklist rapide","Un checklist rápido"),
      [T("Same numbers as my platform · rules per prop account · payout conditions · copy trading counted once · a trade logged in seconds · discipline on the same screen · a daily routine · full export · free to try without a card.","Mêmes chiffres que ma plateforme · règles par compte prop · conditions de payout · copy trading compté une fois · un trade ajouté en quelques secondes · discipline sur le même écran · une routine quotidienne · export complet · essai gratuit sans carte.","Mismos números que mi plataforma · reglas por cuenta prop · condiciones de payout · copy trading contado una vez · una operación en segundos · disciplina en la misma pantalla · una rutina diaria · exportación completa · prueba gratis sin tarjeta.")]),
    ]
    return _article(lang, t, T("How to choose a trading journal for prop firm accounts.","Bien choisir son journal de trading pour les prop firms.","Cómo elegir un diario de trading para cuentas de fondeo."),
        T("Five things that matter when you trade evaluations and funded futures accounts.","Cinq choses qui comptent quand tu trades des évaluations et des comptes financés.","Cinco cosas que importan cuando operas evaluaciones y cuentas fondeadas de futuros."), T("Guide","Guide","Guía"), S,
        [("trading-templates.html",T("Free templates","Modèles gratuits","Plantillas gratuitas")),("trading-journal-routine.html",T("A daily routine","Une routine quotidienne","Una rutina diaria")),("pricing.html",T("Sweep pricing","Tarifs de Sweep","Precios de Sweep"))],
        T("How to choose a trading journal for prop firms · Sweep","Bien choisir son journal de trading pour prop firms · Sweep","Cómo elegir un diario de trading para prop firms · Sweep"),
        T("What to look for in a futures trading journal when you trade prop firm evaluations and funded accounts: accurate P&L, firm rules, fast logging and discipline.","Ce qu’il faut chercher dans un journal de trading de futures quand tu trades des évaluations et des comptes financés : P&L exact, règles des firmes, saisie rapide et discipline.","Qué buscar en un diario de trading de futuros si operas evaluaciones y cuentas fondeadas: P&L exacto, reglas de las firmas, registro rápido y disciplina."))

def page_routine(lang, t):
    S = [
     (T("Before the open: 5 minutes","Avant l’ouverture : 5 minutes","Antes de la apertura: 5 minutos"),
      [T("Write your bias in one sentence, mark the key levels, and describe two scenarios: what you do if price goes one way, and what you do if it goes the other. Set your max loss and max trades for the day, and check the economic releases scheduled during your session.","Écris ton biais en une phrase, note les niveaux clés et décris deux scénarios : ce que tu fais si le prix va dans un sens, et ce que tu fais s’il va dans l’autre. Fixe ta perte max et tes trades max du jour, et regarde les annonces économiques prévues pendant ta séance.","Escribe tu sesgo en una frase, marca los niveles clave y describe dos escenarios: qué haces si el precio va en un sentido y qué haces si va en el otro. Fija tu pérdida máxima y tus operaciones máximas del día y revisa los datos económicos previstos en tu sesión.")]),
     (T("During the session: one line per trade","Pendant la séance : une ligne par trade","Durante la sesión: una línea por operación"),
      [T("Log each trade right after you close it: time, contract, size, entry, exit, result in R, and whether it was in your plan. Answer your discipline checklist honestly. If you hit your max loss or max trades, the session is over.","Note chaque trade juste après l’avoir fermé : heure, contrat, taille, entrée, sortie, résultat en R, et s’il était dans ton plan. Réponds honnêtement à ta checklist de discipline. Si tu atteins ta perte max ou tes trades max, la séance est finie.","Registra cada operación justo al cerrarla: hora, contrato, tamaño, entrada, salida, resultado en R y si estaba en tu plan. Responde con honestidad tu checklist de disciplina. Si alcanzas tu pérdida o tus operaciones máximas, la sesión ha terminado.")]),
     (T("After the close: 60 seconds","Après la clôture : 60 secondes","Tras el cierre: 60 segundos"),
      [T("Three questions are enough: what went well, one thing to improve tomorrow, and did you follow your plan. Rate your discipline from 1 to 5. Keep it short so you do it every day.","Trois questions suffisent : ce qui a bien marché, une chose à améliorer demain, et as-tu suivi ton plan. Note ta discipline de 1 à 5. Garde ça court pour le faire chaque jour.","Bastan tres preguntas: qué salió bien, una cosa a mejorar mañana y si seguiste tu plan. Puntúa tu disciplina de 1 a 5. Hazlo breve para hacerlo cada día.")]),
     (T("Every Friday: the weekly review","Chaque vendredi : la revue de la semaine","Cada viernes: la revisión semanal"),
      [T("Look at the week as a whole: P&L, win rate, trades in your plan, best and worst day. Find the one mistake that cost you the most, and turn it into one rule for next week. One rule, not five.","Regarde la semaine dans son ensemble : P&L, taux de réussite, trades dans ton plan, meilleure et pire journée. Trouve l’erreur qui t’a coûté le plus, et transforme-la en une règle pour la semaine prochaine. Une règle, pas cinq.","Mira la semana en conjunto: P&L, tasa de acierto, operaciones dentro del plan, mejor y peor día. Encuentra el error que más te costó y conviértelo en una regla para la próxima semana. Una regla, no cinco.")]),
     (T("Why it works","Pourquoi ça marche","Por qué funciona"),
      [T("The routine separates what you control from what you don’t. Over weeks, your journal shows which setups, sessions and habits actually make or cost you money, in your own numbers.","La routine sépare ce que tu contrôles de ce que tu ne contrôles pas. Au fil des semaines, ton journal montre quels setups, sessions et habitudes te rapportent ou te coûtent vraiment, dans tes propres chiffres.","La rutina separa lo que controlas de lo que no. Con las semanas, tu diario muestra qué setups, sesiones y hábitos te hacen ganar o perder dinero de verdad, en tus propios números.")]),
    ]
    return _article(lang, t, T("A daily trading journal routine that sticks.","Une routine de journal de trading qui tient dans le temps.","Una rutina diaria de diario de trading que funciona."),
        T("Five minutes before the open, one line per trade, sixty seconds after the close.","Cinq minutes avant l’ouverture, une ligne par trade, soixante secondes après la clôture.","Cinco minutos antes de la apertura, una línea por operación, sesenta segundos tras el cierre."), T("Guide","Guide","Guía"), S,
        [("trading-templates.html",T("Free templates","Modèles gratuits","Plantillas gratuitas")),("how-to-choose-a-trading-journal.html",T("Choose a trading journal","Choisir un journal","Elegir un diario")),("release-dates.html",T("Release dates","Dates des annonces","Fechas de datos"))],
        T("Daily trading journal routine: before, during and after the session · Sweep","Routine de journal de trading : avant, pendant et après la séance · Sweep","Rutina de diario de trading: antes, durante y después de la sesión · Sweep"),
        T("A simple daily routine for your trading journal: a 5-minute plan before the open, one line per trade, a 60-second review after the close and a weekly review.","Une routine simple pour ton journal : un plan de 5 minutes avant l’ouverture, une ligne par trade, une revue de 60 secondes après la clôture et une revue de la semaine.","Una rutina sencilla para tu diario: un plan de 5 minutos antes de la apertura, una línea por operación, una revisión de 60 segundos al cierre y una revisión semanal."))
