from core import *
import re

def fm(m):
    return lambda *a, **k: frame(*a, mobile=m, **k)

AI_FEATURES = [
 ("spark", T("Log in plain words","Saisie en mots simples","Registra con tus palabras"),
  T("“2 NQ longs at the London open, first stopped at −12 ticks, second +30 at target” becomes draft trades you check and save.","« 2 longs NQ à l’ouverture de Londres, le premier stoppé à −12 ticks, le second +30 à la cible » devient des brouillons de trades à vérifier et enregistrer.","«2 largos en NQ en la apertura de Londres, el primero en stop a −12 ticks, el segundo +30 en objetivo» se convierte en borradores que revisas y guardas.")),
 ("image", T("Import a screenshot","Importe une capture","Importa una captura"),
  T("A fills or trade-history screenshot becomes draft trades, ready to check.","Une capture d’exécutions ou d’historique devient des brouillons de trades, prêts à vérifier.","Una captura de ejecuciones o historial se convierte en borradores listos para revisar.")),
 ("chat", T("Ask your journal","Interroge ton journal","Pregunta a tu diario"),
  T("“Win rate on NQ after 10:30?” The AI understands the question; Sweep calculates the number from your own trades.","« Mon taux de réussite sur NQ après 10 h 30? » L’IA comprend la question; Sweep calcule le chiffre à partir de tes propres trades.","«¿Mi tasa de acierto en NQ después de las 10:30?» La IA entiende la pregunta; Sweep calcula el número con tus operaciones.")),
 ("calendar", T("Weekly review","Bilan de la semaine","Revisión semanal"),
  T("A process score out of 10, what went well, what to fix, one focus and one rule for next week.","Un score de processus sur 10, ce qui a bien été, ce qu’il faut corriger, un focus et une règle pour la semaine suivante.","Una puntuación de proceso sobre 10, lo que fue bien, lo que corregir, un enfoque y una regla para la próxima semana.")),
 ("check", T("Day debrief","Débrief de la journée","Resumen del día"),
  T("Plan against execution for a journaled day: verdict, checks, lesson and one action for tomorrow.","Plan contre exécution pour une journée notée : verdict, vérifications, leçon et une action pour demain.","Plan frente a ejecución de un día registrado: veredicto, comprobaciones, lección y una acción para mañana.")),
 ("doc", T("Trade feedback","Avis sur un trade","Opinión sobre una operación"),
  T("What went well, what to improve and what to do next time. It can read the trade’s chart screenshot.","Ce qui a bien été, ce qu’il faut améliorer et quoi faire la prochaine fois. Il peut lire la capture du graphique.","Lo que fue bien, qué mejorar y qué hacer la próxima vez. Puede leer la captura del gráfico.")),
 ("tag", T("Setup suggestion","Suggestion de setup","Sugerencia de setup"),
  T("Suggests the setup and tags from your own list, applied in one tap.","Suggère le setup et les tags à partir de ta propre liste, appliqués en un toucher.","Sugiere el setup y las etiquetas de tu propia lista, aplicados en un toque.")),
 ("receipt", T("Scan a receipt","Scanne un reçu","Escanea un recibo"),
  T("Evaluation invoices, reset fees, data fees and payout emails become expenses or payouts to check and save.","Factures d’évaluation, frais de reset, frais de données et courriels de payout deviennent des dépenses ou des payouts à vérifier.","Facturas de evaluación, reinicios, cuotas de datos y correos de payout se convierten en gastos o payouts para revisar.")),
]

AI_FAQ = [
 (T("What is Ask Sweep?","Qu’est-ce que Ask Sweep?","¿Qué es Ask Sweep?"),
  T("The chat assistant in the corner of the app. Ask about your trades, today’s U.S. news or how to use Sweep. Numbers about your trading are calculated by Sweep from your journal.",
    "L’assistant de discussion dans le coin de l’app. Pose tes questions sur tes trades, les nouvelles américaines du jour ou l’utilisation de Sweep. Les chiffres sur ton trading sont calculés par Sweep à partir de ton journal.",
    "El asistente de chat en la esquina de la app. Pregunta por tus operaciones, las noticias de EE. UU. de hoy o cómo usar Sweep. Las cifras de tu trading las calcula Sweep con tu diario.")),
 (T("How fast are economic numbers updated?","À quelle vitesse les chiffres économiques sont-ils mis à jour?","¿Qué tan rápido se actualizan las cifras económicas?"),
  T("A flash recap about a minute after the release, a full market report after about 30 minutes, and a final update about 3 hours later. Updates run while traders use the app, so timing can occasionally be a little later.",
    "Un récap éclair environ une minute après la publication, un rapport de marché complet après environ 30 minutes, et une dernière mise à jour environ 3 heures plus tard. Les mises à jour se font pendant que les traders utilisent l’app : le délai peut parfois être un peu plus long.",
    "Un resumen flash aproximadamente un minuto después de la publicación, un informe completo tras unos 30 minutos y una última actualización unas 3 horas después. Las actualizaciones ocurren mientras los traders usan la app, así que a veces pueden tardar un poco más.")),
 (T("Where do the economic numbers come from?","D’où viennent les chiffres économiques?","¿De dónde vienen las cifras económicas?"),
  T("Official releases (BLS, BEA, Federal Reserve, ISM, Conference Board…) and major financial news, found with Google Search. Every report lists its sources, and a figure stays empty until it can be confirmed.",
    "Des publications officielles (BLS, BEA, Réserve fédérale, ISM, Conference Board…) et de grands médias financiers, trouvés avec la Recherche Google. Chaque rapport liste ses sources, et un chiffre reste vide tant qu’il n’est pas confirmé.",
    "De publicaciones oficiales (BLS, BEA, Reserva Federal, ISM, Conference Board…) y grandes medios financieros, encontrados con la Búsqueda de Google. Cada informe lista sus fuentes y una cifra queda vacía hasta que se confirma.")),
 (T("Is there a limit on AI?","Y a-t-il une limite à l’IA?","¿Hay un límite de IA?"),
  T("Yes. Sweep AI is included according to your plan: a base quota on Free, an extended quota on Pro and the maximum quota on Elite. Repeating the exact same request doesn’t count again.","Oui. Sweep AI est inclus selon le forfait : quota de base en Free, quota élargi en Pro et quota maximal en Elite. Refaire exactement la même demande ne compte pas de nouveau.","Sí. Sweep AI está incluido según tu plan: cuota básica en Free, ampliada en Pro y máxima en Elite. Repetir exactamente la misma solicitud no cuenta de nuevo.")),
 (T("Can Sweep AI tell me what to trade?","Sweep AI peut-il me dire quoi trader?","¿Sweep AI puede decirme qué operar?"),
  T("No. It only looks at your own past trades and public news. No signals, no predictions, no entries or exits.",
    "Non. Il ne regarde que tes propres trades passés et les nouvelles publiques. Ni signaux, ni prédictions, ni entrées ou sorties.",
    "No. Solo mira tus operaciones pasadas y las noticias públicas. Sin señales, predicciones, entradas ni salidas.")),
 (T("What data does Sweep AI send, and when?","Quelles données Sweep AI envoie-t-il, et quand?","¿Qué datos envía Sweep AI y cuándo?"),
  T("Nothing is sent until you tap an AI action. Then only what that action needs, for example your text, the screenshot you chose, or short summaries of your stats, goes to the AI provider. Settings → Sweep AI explains it in detail, and the Privacy policy lists the provider.",
    "Rien n’est envoyé tant que tu ne touches pas une action IA. Ensuite, seul ce dont l’action a besoin (ton texte, la capture choisie ou de courts résumés de tes stats) est transmis au fournisseur d’IA. Réglages → Sweep AI l’explique en détail, et la politique de confidentialité nomme le fournisseur.",
    "No se envía nada hasta que tocas una acción de IA. Después, solo lo que esa acción necesita (tu texto, la captura elegida o breves resúmenes de tus estadísticas) va al proveedor de IA. Ajustes → Sweep AI lo explica en detalle y la Política de privacidad nombra al proveedor.")),
]

def ai_band(lang, t, short=False):
    SHORT = {"ai-log-trades": T("Describe the trade. Sweep fills the ticket.","Décris le trade. Sweep remplit le ticket.","Describe la operación. Sweep llena el ticket."),
             "ask-sweep": T("Questions about your trading, answered with your own numbers.","Tes questions sur ton trading, avec tes propres chiffres.","Preguntas sobre tu trading, con tus propios números."),
             "news-impact-report": T("A recap about a minute after every U.S. release.","Un récap environ une minute après chaque annonce américaine.","Un resumen aproximadamente un minuto después de cada dato de EE. UU.")}
    card = lambda dscreen, mscreen, h, p, cap=None: f'''<article class="pillar"><div class="txt"><span class="spark-tag">✦ Sweep AI</span><h3>{t(h)}</h3><p>{t(SHORT[dscreen] if short else p)}</p></div><div class="shot">{picture_dm(dscreen,mscreen,lang,t(h))}</div></article>'''
    return f'''<section class="rule ai-band"><div class="wrap">
<div class="head"><span class="kick">{t(T("New","Nouveau","Nuevo"))}</span><h2>{t(T("Your journal, now with AI.","Ton journal, maintenant avec l’IA.","Tu diario, ahora con IA."))}</h2>
<p class="lead">{t(T("Describe a trade in plain words, ask your journal anything, read a recap after every U.S. release. You approve every draft. Sweep does the math.","Décris un trade en mots simples, pose n’importe quelle question à ton journal, lis un récap après chaque annonce américaine. Tu approuves chaque brouillon. Sweep fait les calculs.","Describe una operación con tus palabras, pregúntale lo que quieras a tu diario, lee un resumen tras cada dato de EE. UU. Tú apruebas cada borrador. Sweep hace las cuentas."))}</p></div>
<div class="pillars stagger">
{card("ai-log-trades","ask-sweep",T("Log in plain words","Saisie en mots simples","Registra con tus palabras"),T("Describe your trades like you would to a friend, or drop a screenshot. Sweep fills the ticket for you to check.","Décris tes trades comme à un ami, ou dépose une capture. Sweep remplit le ticket, tu vérifies.","Describe tus operaciones como a un amigo, o suelta una captura. Sweep llena el ticket y tú lo revisas."))}
{card("ask-sweep","ask-sweep",T("Ask your journal","Interroge ton journal","Pregunta a tu diario"),T("“Which setup makes me the most money?” Ask Sweep answers from your own trades, with numbers Sweep calculates.","« Quel setup me rapporte le plus? » Ask Sweep répond à partir de tes trades, avec des chiffres calculés par Sweep.","«¿Qué setup me da más dinero?» Ask Sweep responde con tus operaciones y cifras calculadas por Sweep."))}
{card("news-impact-report","news-impact-report",T("A report after every release","Un rapport après chaque annonce","Un informe tras cada dato"),T("A flash recap about a minute after U.S. releases, then a full read on NQ, ES, yields and the dollar at 30 minutes.","Un récap éclair environ une minute après les annonces américaines, puis une lecture complète sur NQ, ES, les taux et le dollar à 30 minutes.","Un resumen flash aproximadamente un minuto después de los datos de EE. UU., y luego una lectura completa de NQ, ES, rendimientos y dólar a los 30 minutos."))}
</div>
<div class="cta-row"><a class="btn btn-line" href="{href(lang,'ai.html')}">{t(T("Discover Sweep AI","Découvrir Sweep AI","Descubrir Sweep AI"))}</a></div>
</div></section>'''

def timeline(t):
    steps = [(T("At release","À la publication","Al publicarse"), T("Numbers fill in","Les chiffres se remplissent","Las cifras se completan"), T("Actual, consensus, previous and revision, from official sources.","Réel, consensus, précédent et révision, de sources officielles.","Real, consenso, anterior y revisión, de fuentes oficiales.")),
             (T("≈ 1 min","≈ 1 min","≈ 1 min"), T("Flash recap","Récap éclair","Resumen flash"), T("The number against consensus and the previous reading, and what it means for the Fed.","Le chiffre contre le consensus et la lecture précédente, et ce que ça signifie pour la Fed.","El dato frente al consenso y al anterior, y lo que significa para la Fed.")),
             (T("≈ 30 min","≈ 30 min","≈ 30 min"), T("Full report","Rapport complet","Informe completo"), T("How NQ, ES, the 10-year yield and the dollar reacted, why, the Fed read and what to watch next.","Comment NQ, ES, le taux 10 ans et le dollar ont réagi, pourquoi, la lecture de la Fed et quoi surveiller.","Cómo reaccionaron NQ, ES, el rendimiento a 10 años y el dólar, por qué, la lectura de la Fed y qué vigilar.")),
             (T("≈ 3 h","≈ 3 h","≈ 3 h"), T("Final update","Mise à jour finale","Actualización final"), T("The report is refreshed once the dust settles.","Le rapport est rafraîchi une fois la poussière retombée.","El informe se actualiza cuando todo se calma."))]
    return '<ol class="timeline stagger">' + "".join(f'<li><span class="when num">{t(w)}</span><h3>{t(h)}</h3><p>{t(p)}</p></li>' for w,h,p in steps) + '</ol>'

def page_ai(lang, t):
    hero = f'''<div class="page-hero ai-hero"><div class="wrap">
<span class="kick">Sweep AI</span><h1 class="wu">{words(t(T("Your journal, now with AI.","Ton journal, maintenant avec l’IA.","Tu diario, ahora con IA.")))}</h1>
<p class="lead">{t(T("Ask questions, find your edge, and prepare for the news, in plain words.","Pose tes questions, trouve ton edge et prépare-toi aux annonces, simplement.","Haz tus preguntas, encuentra tu edge y prepárate para las noticias, con palabras simples."))}</p><p class="fine">{t(T("AI answers come from your own journal. They’re not trading advice.","Les réponses viennent de ton propre journal. Ce ne sont pas des conseils de trading.","Las respuestas vienen de tu propio diario. No son consejos de trading."))}</p>
<div class="cta-row"><a class="btn btn-primary btn-lg" href="{SIGNUP}">{t(CREATE_FREE)}</a><a class="btn btn-line btn-lg" href="#features">{t(T("What it does","Ce qu’il fait","Qué hace"))}</a></div>
<p class="meta">{t(T("Sweep AI is included according to your plan. Never financial advice, never market predictions.","Sweep AI est inclus selon le forfait. Jamais de conseil financier, jamais de prédiction de marché.","Sweep AI está incluido según tu plan. Nunca asesoramiento financiero, nunca predicciones de mercado."))}</p>
<div class="reveal" style="margin-top:56px">{fm("ask-sweep")("ai-log-trades",lang,t(T("Sweep AI turning a sentence into a draft trade","Sweep AI transforme une phrase en brouillon de trade","Sweep AI convierte una frase en un borrador de operación")),t,eager=True)}</div>
</div></div>'''
    g = f'''<section id="features" class="rule"><div class="wrap"><div class="head"><span class="kick">{t(T("Eight AI actions","Huit actions IA","Ocho acciones de IA"))}</span><h2>{t(T("Less typing. More reviewing.","Moins de saisie. Plus de révision.","Menos escribir. Más revisar."))}</h2>
<p class="lead">{t(T("Sweep AI appears only when you tap an AI action, marked ✦ in the app. It works in English, French and Spanish.","Sweep AI n’apparaît que quand tu touches une action IA, marquée ✦ dans l’app. Il fonctionne en anglais, en français et en espagnol.","Sweep AI aparece solo cuando tocas una acción de IA, marcada con ✦ en la app. Funciona en inglés, francés y español."))}</p></div>
{grid(t, AI_FEATURES, "g4")}</div></section>'''
    S = split(t, T("Log with AI","Saisie avec l’IA","Registrar con IA"), T("Describe the trade. Sweep fills the ticket.","Décris le trade. Sweep remplit le ticket.","Describe la operación. Sweep llena el ticket."),
        T("Type it like a message or import a screenshot of your fills. Sweep turns it into draft trades with account, instrument, size, prices and times. Nothing is saved until you check it.","Écris-le comme un message ou importe une capture de tes exécutions. Sweep en fait des brouillons avec compte, instrument, taille, prix et heures. Rien n’est enregistré avant ta vérification.","Escríbelo como un mensaje o importa una captura de tus ejecuciones. Sweep lo convierte en borradores con cuenta, instrumento, tamaño, precios y horas. Nada se guarda hasta que lo revisas."),
        [T("“✦ Log with AI” right in the trade ticket","« ✦ Saisir avec l’IA » directement dans le ticket","«✦ Registrar con IA» directamente en el ticket"),
         T("Several trades from one sentence","Plusieurs trades à partir d’une seule phrase","Varias operaciones a partir de una frase"),
         T("Fills and trade-history screenshots","Captures d’exécutions et d’historique","Capturas de ejecuciones e historial")],
        frame("ticket-log-with-ai", lang, t(T("Log with AI button in the trade ticket","Bouton Saisir avec l’IA dans le ticket","Botón Registrar con IA en el ticket")), t, swap=False))
    S += split(t, T("Ask Sweep","Ask Sweep","Ask Sweep"), T("Ask Sweep anything about your trading.","Demande tout à Sweep sur ton trading.","Pregúntale a Sweep lo que quieras sobre tu trading."),
        T("Ask Sweep, your trading assistant, lives in the corner of the app. Ask about your results, today’s U.S. news or how to use Sweep. It suggests follow-up questions and can open the right page in one tap.","Ask Sweep, ton assistant de trading, vit dans le coin de l’app. Pose tes questions sur tes résultats, les nouvelles américaines du jour ou l’utilisation de Sweep. Il propose des questions de suivi et ouvre la bonne page en un toucher.","Ask Sweep, tu asistente de trading, vive en la esquina de la app. Pregunta por tus resultados, las noticias de EE. UU. de hoy o cómo usar Sweep. Sugiere preguntas de seguimiento y abre la página correcta en un toque."),
        [T("“How did I do this week?” “How do I do after a loss?”","« Comment s’est passée ma semaine? » « Comment je trade après une perte? »","«¿Cómo me fue esta semana?» «¿Cómo opero después de una pérdida?»"),
         T("Numbers calculated by Sweep from your journal","Chiffres calculés par Sweep à partir de ton journal","Cifras calculadas por Sweep con tu diario"),
         T("No predictions, no signals, and it says so kindly","Ni prédictions ni signaux, et il le dit gentiment","Sin predicciones ni señales, y lo dice con amabilidad")],
        frame("ask-sweep", lang, t(T("Ask Sweep chat answering a question about setups","Ask Sweep répond à une question sur les setups","Ask Sweep responde una pregunta sobre setups")), t), flip=True, id_="ask-sweep")
    S += split(t, T("Reviews","Bilans","Revisiones"), T("A coach’s read on your week, in seconds.","La lecture d’un coach sur ta semaine, en quelques secondes.","La lectura de un coach sobre tu semana, en segundos."),
        T("The weekly review scores your process out of 10 and ends with one focus and one rule for next week. The day debrief compares your plan with what you did. A Discord-ready recap can be copied in one tap.","Le bilan hebdo note ton processus sur 10 et se termine par un focus et une règle pour la semaine suivante. Le débrief de la journée compare ton plan à ce que tu as fait. Un récap prêt pour Discord se copie en un toucher.","La revisión semanal puntúa tu proceso sobre 10 y termina con un enfoque y una regla para la próxima semana. El resumen del día compara tu plan con lo que hiciste. Un resumen listo para Discord se copia en un toque."),
        [], frame("ai-weekly-review", lang, t(T("AI weekly review with process score","Bilan hebdo IA avec score de processus","Revisión semanal IA con puntuación de proceso")), t, swap=False))
    S += split(t, T("Trade feedback","Avis sur un trade","Opinión sobre la operación"), T("Feedback on every trade, if you want it.","Un avis sur chaque trade, si tu le veux.","Una opinión sobre cada operación, si la quieres."),
        T("From the trade review, get what went well, what to improve and what to do next time. Sweep AI can read your chart screenshot and suggest the setup and tags from your own list.","Depuis la révision du trade, obtiens ce qui a bien été, ce qu’il faut améliorer et quoi faire la prochaine fois. Sweep AI peut lire ta capture de graphique et suggérer le setup et les tags de ta liste.","Desde la revisión, obtén lo que fue bien, qué mejorar y qué hacer la próxima vez. Sweep AI puede leer tu captura del gráfico y sugerir el setup y las etiquetas de tu lista."),
        [], frame("ai-trade-feedback", lang, t(T("AI feedback on a trade","Avis de l’IA sur un trade","Opinión de la IA sobre una operación")), t, swap=False), flip=True)
    S += split(t, T("Economic calendar","Calendrier économique","Calendario económico"), T("Every U.S. release, recapped in a minute.","Chaque annonce américaine, résumée en une minute.","Cada dato de EE. UU., resumido en un minuto."),
        T("Numbers fill themselves in from official sources, with a flash recap about a minute after the release and a full market reaction report after about 30 minutes.","Les chiffres se remplissent seuls à partir de sources officielles, avec un récap éclair environ une minute après la publication et un rapport complet sur la réaction du marché après environ 30 minutes.","Las cifras se completan solas desde fuentes oficiales, con un resumen flash aproximadamente un minuto después y un informe completo de la reacción del mercado tras unos 30 minutos."),
        [], frame("news-impact-report", lang, t(T("Market impact report after Nonfarm Payrolls","Rapport d’impact après le Nonfarm Payrolls","Informe de impacto tras el Nonfarm Payrolls")), t, cap=EXAMPLE),
        more=f'<div class="cta-row"><a class="btn btn-line" href="{href(lang,"economic-calendar.html")}">{t(T("How the reports work","Comment fonctionnent les rapports","Cómo funcionan los informes"))}</a></div>')
    honest = f'''<section class="rule"><div class="wrap"><div class="head"><span class="kick">{t(T("How we keep it honest","Comment on reste honnête","Cómo lo mantenemos honesto"))}</span><h2>{t(T("AI that helps you review, never trade for you.","Une IA qui t’aide à réviser, jamais à trader à ta place.","IA que te ayuda a revisar, nunca opera por ti."))}</h2></div>
{grid(t,[("eye",T("Drafts you check","Des brouillons à vérifier","Borradores que revisas"),T("Nothing the AI writes is saved until you check it.","Rien de ce que l’IA écrit n’est enregistré avant ta vérification.","Nada de lo que escribe la IA se guarda hasta que lo revisas.")),
("net",T("Math by Sweep","Les calculs par Sweep","Las cuentas, por Sweep"),T("Stats come from your journal, calculated by Sweep, not guessed.","Les stats viennent de ton journal, calculées par Sweep, pas devinées.","Las estadísticas salen de tu diario, calculadas por Sweep, no adivinadas.")),
("doc",T("Sources shown","Sources affichées","Fuentes visibles"),T("Every market report lists its sources and a confidence level.","Chaque rapport de marché liste ses sources et un niveau de confiance.","Cada informe de mercado lista sus fuentes y un nivel de confianza.")),
("shield",T("No signals","Aucun signal","Sin señales"),T("No predictions, no entries or exits, no financial advice.","Ni prédictions, ni entrées ou sorties, ni conseils financiers.","Sin predicciones, entradas, salidas ni asesoramiento financiero."))],"g4")}
<p class="meta" style="margin-top:22px">{t(T("AI can be wrong. Nothing is sent to the AI provider until you tap an AI action. Deleting your account also deletes its AI history.","L’IA peut se tromper. Rien n’est envoyé au fournisseur d’IA tant que tu ne touches pas une action IA. Supprimer ton compte supprime aussi son historique IA.","La IA puede equivocarse. No se envía nada al proveedor de IA hasta que tocas una acción de IA. Eliminar tu cuenta también elimina su historial de IA."))} <a href="{href(lang,'privacy.html')}">{t(T("Privacy policy","Politique de confidentialité","Política de privacidad"))}</a></p></div></section>'''
    faq = f'''<section class="rule"><div class="wrap narrow"><div class="head"><h2>{t(T("Sweep AI questions","Questions sur Sweep AI","Preguntas sobre Sweep AI"))}</h2></div>{"".join(faq_item(t,q,a) for q,a in AI_FAQ)}</div></section>'''
    ld = jsonld({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":t(q),"acceptedAnswer":{"@type":"Answer","text":t(a)}} for q,a in AI_FAQ]})
    return (t(T("Sweep AI · AI trading journal for futures traders","Sweep AI · Journal de trading avec IA pour traders de futures","Sweep AI · Diario de trading con IA para traders de futuros")),
            t(T("Log trades in plain words or from screenshots, ask your journal anything, get AI weekly reviews, trade feedback and U.S. economic release reports. No signals, drafts you check.","Note tes trades en mots simples ou par capture, interroge ton journal, reçois des bilans hebdo IA, des avis sur tes trades et des rapports sur les annonces américaines. Aucun signal, des brouillons à vérifier.","Registra operaciones con tus palabras o capturas, pregunta a tu diario, recibe revisiones semanales con IA, opiniones sobre tus operaciones e informes de datos de EE. UU. Sin señales, borradores que revisas.")),
            hero + g + S + honest + faq + final_cta(lang, t), ld)

def page_econ(lang, t):
    hero = page_hero(t, T("Every U.S. release, recapped in a minute.","Chaque annonce américaine, résumée en une minute.","Cada dato de EE. UU., resumido en un minuto."),
        T("High and medium impact U.S. releases in Eastern Time. The numbers fill themselves in, a flash recap lands about a minute after the release, and a full market reaction report follows at about 30 minutes. All of it linked to your trades.","Les annonces américaines d’impact élevé et moyen, en heure de l’Est. Les chiffres se remplissent seuls, un récap éclair arrive environ une minute après la publication, puis un rapport complet sur la réaction du marché vers 30 minutes. Le tout lié à tes trades.","Datos de EE. UU. de impacto alto y medio, en hora del Este. Las cifras se completan solas, un resumen flash llega aproximadamente un minuto después y un informe completo de la reacción del mercado a los 30 minutos. Todo vinculado a tus operaciones."),
        T("Economic calendar","Calendrier économique","Calendario económico"), f'<a class="btn btn-primary btn-lg" href="{SIGNUP}">{t(CREATE_FREE)}</a>')
    b = f'<section style="padding-top:16px"><div class="wrap">{frame("news-impact-report",lang,t(T("Nonfarm Payrolls detail with market impact report","Détail du Nonfarm Payrolls avec rapport d’impact","Detalle del Nonfarm Payrolls con informe de impacto")),t,eager=True,cap=EXAMPLE)}</div></section>'
    b += f'''<section class="rule"><div class="wrap"><div class="head"><span class="kick">{t(T("After every release","Après chaque annonce","Tras cada dato"))}</span><h2>{t(T("From the number to the market’s answer.","Du chiffre à la réponse du marché.","Del dato a la respuesta del mercado."))}</h2>
<p class="lead">{t(T("Updates run while traders use the app, so timing can occasionally be a little later.","Les mises à jour se font pendant que les traders utilisent l’app : le délai peut parfois être un peu plus long.","Las actualizaciones ocurren mientras los traders usan la app, así que a veces pueden tardar un poco más."))}</p></div>{timeline(t)}</div></section>'''
    b += split(t, T("Inside a report","Dans un rapport","Dentro de un informe"), T("What moved, why, and what to watch next.","Ce qui a bougé, pourquoi, et quoi surveiller.","Qué se movió, por qué y qué vigilar."),
        T("The full report reads the reaction across four markets, explains the move, gives the Fed read and the next catalyst. Reports are written in English, French and Spanish.","Le rapport complet lit la réaction sur quatre marchés, explique le mouvement, donne la lecture de la Fed et le prochain catalyseur. Les rapports sont rédigés en anglais, en français et en espagnol.","El informe completo lee la reacción en cuatro mercados, explica el movimiento, da la lectura de la Fed y el próximo catalizador. Los informes se escriben en inglés, francés y español."),
        [], frame("news-impact-report", lang, t(T("Market impact report","Rapport d’impact","Informe de impacto")), t, cap=EXAMPLE, swap=False) if False else frame("economic-calendar",lang,t(T("Economic calendar in Sweep","Calendrier économique dans Sweep","Calendario económico en Sweep")),t),
        more='<div class="chips" style="margin-top:26px">' + "".join(f"<span>{x}</span>" for x in ["NQ","ES","US10Y","USD"]) + "</div>" + f'''<ul class="list">{"".join(f"<li>{t(x)}</li>" for x in [T("<b>Sources</b> linked in every report, with a confidence level","<b>Sources</b> en lien dans chaque rapport, avec un niveau de confiance","<b>Fuentes</b> enlazadas en cada informe, con nivel de confianza"),
         T("<b>Labeled values:</b> figures found by Sweep AI are marked in the event’s details","<b>Valeurs identifiées :</b> les chiffres trouvés par Sweep AI sont indiqués dans le détail de l’événement","<b>Valores identificados:</b> las cifras encontradas por Sweep AI se indican en el detalle del evento"),
         T("<b>Never a guess:</b> a figure stays empty until it’s confirmed","<b>Jamais deviné :</b> un chiffre reste vide tant qu’il n’est pas confirmé","<b>Nunca adivinado:</b> una cifra queda vacía hasta que se confirma"),
         T("<b>Consensus</b> for the next 7 days filled in too","<b>Consensus</b> des 7 prochains jours rempli aussi","<b>Consenso</b> de los próximos 7 días también completado")])}</ul>''')
    b += split(t, T("On your trades","Sur tes trades","En tus operaciones"), T("Every trade knows what was released around it.","Chaque trade sait ce qui est sorti autour.","Cada operación sabe qué se publicó a su alrededor."),
      T("Sweep links each saved trade to the U.S. events from 30 minutes before entry to 30 minutes after exit, and shows the timing, for example “2m 00s after the release”.","Sweep lie chaque trade aux événements américains de 30 minutes avant l’entrée à 30 minutes après la sortie, et montre le délai, par exemple « 2 min 00 s après la publication ».","Sweep vincula cada operación a los eventos de EE. UU. desde 30 minutos antes de la entrada hasta 30 después de la salida, y muestra el tiempo, por ejemplo «2 min 00 s después de la publicación»."),
      [T("A warning in the trade ticket when a release is close","Un avertissement dans le ticket quand une publication approche","Un aviso en el ticket cuando se acerca una publicación"),
       T("High-impact news in each day of the P&L calendar, like “08:30 CPI”","Les nouvelles importantes dans chaque jour du calendrier P&L, comme « 08:30 CPI »","Noticias de alto impacto en cada día del calendario de P&L, como «08:30 CPI»"),
       T("Insights on trades within 5 or 15 minutes of a release versus the rest","Analyses des trades à 5 ou 15 minutes d’une publication par rapport aux autres","Análisis de operaciones a 5 o 15 minutos de una publicación frente al resto")],
      frame("calendar",lang,t(T("P&L calendar with daily news","Calendrier P&L avec les nouvelles du jour","Calendario de P&L con noticias del día")),t), flip=True)
    from pages2 import INDICATORS
    rows = [(T("Scope","Portée","Alcance"),T("U.S. events, high and medium impact","Événements américains, impact élevé et moyen","Eventos de EE. UU., impacto alto y medio")),
            (T("Time zone","Fuseau horaire","Zona horaria"),T("Eastern Time (New York)","Heure de l’Est (New York)","Hora del Este (Nueva York)")),
            (T("Schedule","Calendrier","Calendario"),T("BLS and Federal Reserve calendars, 2026–2027. “est.” marks dates projected until the official date is published","Calendriers du BLS et de la Réserve fédérale, 2026–2027. « est. » indique une date projetée en attendant la date officielle","Calendarios del BLS y la Reserva Federal, 2026–2027. «est.» indica una fecha proyectada hasta la oficial")),
            (T("Values","Valeurs","Valores"),T("Actual, consensus, previous and revision, looked up by Sweep AI from official releases and major financial news","Réel, consensus, précédent et révision, trouvés par Sweep AI dans les publications officielles et les grands médias financiers","Real, consenso, anterior y revisión, buscados por Sweep AI en publicaciones oficiales y grandes medios financieros")),
            (T("Reports","Rapports","Informes"),T("Flash at about 1 minute, full at about 30 minutes, final at about 3 hours, in each language","Éclair vers 1 minute, complet vers 30 minutes, final vers 3 heures, dans chaque langue","Flash hacia 1 minuto, completo hacia 30 minutos, final hacia 3 horas, en cada idioma")),
            (T("Explainers","Explications","Explicaciones"),T("19 major indicators explained in plain words","19 indicateurs majeurs expliqués en mots simples","19 indicadores principales explicados en palabras simples"))]
    b += f'<section class="rule"><div class="wrap narrow"><div class="head"><h2>{t(T("What’s covered","Ce qui est couvert","Qué cubre"))}</h2></div><table class="tbl"><tbody>' + "".join(f"<tr><th>{t(a)}</th><td>{t(c)}</td></tr>" for a,c in rows) + "</tbody></table>"
    b += '<div class="chips" style="margin-top:28px">' + "".join(f"<span>{i}</span>" for i in INDICATORS) + "</div>"
    b += f'<p class="meta" style="margin-top:28px">{t(T("Reports are AI-generated from public news. They can be delayed, incomplete or wrong, and they are not financial advice. Always check the official release.","Les rapports sont générés par IA à partir de nouvelles publiques. Ils peuvent être en retard, incomplets ou erronés, et ne sont pas des conseils financiers. Vérifie toujours la publication officielle.","Los informes se generan con IA a partir de noticias públicas. Pueden llegar tarde, estar incompletos o ser erróneos, y no son asesoramiento financiero. Verifica siempre la publicación oficial."))}</p></div></section>'
    return (t(T("Economic calendar for futures traders · CPI, NFP, FOMC · Sweep","Calendrier économique pour traders de futures · Sweep","Calendario económico para traders de futuros · Sweep")),
            t(T("U.S. economic releases with numbers filled in automatically, a flash recap about a minute after the release and a market reaction report on NQ, ES, yields and the dollar at 30 minutes.","Annonces économiques américaines avec chiffres remplis automatiquement, récap éclair environ une minute après la publication et rapport de réaction sur NQ, ES, les taux et le dollar à 30 minutes.","Datos económicos de EE. UU. con cifras completadas automáticamente, resumen flash aproximadamente un minuto después y un informe de reacción en NQ, ES, rendimientos y dólar a los 30 minutos.")),
            hero + b + final_cta(lang, t), "")
