import asyncio
from playwright.async_api import async_playwright
B='http://127.0.0.1:8095'
async def main():
  async with async_playwright() as p:
    br=await p.chromium.launch()
    ctx=await br.new_context(viewport={'width':1440,'height':900}, storage_state='/tmp/show_state.json', color_scheme='dark', locale='en-US'); pg=await ctx.new_page()
    await pg.add_init_script("sessionStorage.setItem('sw.modal','1'); localStorage.setItem('tj.lang', JSON.stringify('en'))")
    await pg.goto(B+'/?x=1#accounts'); await pg.wait_for_timeout(3000)
    names=lambda: pg.evaluate("[...document.querySelectorAll('#main table.acct-tbl tr[data-href^=\"#account/\"]')].map(r=>r.firstElementChild.innerText.trim()).join(' | ')")
    print('before:', await names(), '| add on top:', await pg.evaluate("(()=>{const a=document.querySelector('#main .surface > .nav-addrow[data-act=acct-add]'); return a? (a.compareDocumentPosition(document.querySelector('#main table.acct-tbl')) & 4 ? 'yes':'no'):'missing'})()"))
    rows=pg.locator('#main table.acct-tbl tr[data-href^="#account/"]')
    await rows.nth(0).drag_to(rows.nth(2)); await pg.wait_for_timeout(1200)
    print('after drag (1st → 3rd):', await names())
    await pg.evaluate("location.hash='#dashboard'"); await pg.wait_for_timeout(2000)
    print('Today accounts card order:', await pg.evaluate("[...document.querySelectorAll('.d-acc .nav-acc b')].map(b=>b.textContent.trim()).slice(0,5).join(' | ')"))
    q=await pg.evaluate("(()=>{const q=document.querySelector('.d-quick'); const g=q.querySelector('.nav-qgrid'); return 'card bottom '+Math.round(q.getBoundingClientRect().bottom)+' | last buttons bottom '+Math.round(g.getBoundingClientRect().bottom)})()"); print('Quick access:', q)
    await pg.screenshot(path='/tmp/ord_today.png')
    await pg.evaluate("location.hash='#accounts'"); await pg.wait_for_timeout(1500); await pg.screenshot(path='/tmp/ord_desk.png')
    await ctx.close()
    ctx=await br.new_context(**p.devices['iPhone 13'], storage_state='/tmp/show_state.json', color_scheme='dark', locale='en-US'); pg=await ctx.new_page(); cdp=await ctx.new_cdp_session(pg)
    await pg.add_init_script("sessionStorage.setItem('sw.modal','1'); localStorage.setItem('tj.lang', JSON.stringify('en'))")
    await pg.goto(B+'/?x=1#accounts'); await pg.wait_for_timeout(3000)
    names=lambda: pg.evaluate("[...document.querySelectorAll('#main table.acct-tbl tr[data-href^=\"#account/\"]')].map(r=>r.firstElementChild.innerText.trim()).join(' | ')")
    await pg.locator('.nav-ord-b').tap(); await pg.wait_for_timeout(400)
    print('phone, reorder mode, handles visible:', await pg.locator('.nav-ord-on .nav-grip:visible').count())
    await pg.screenshot(path='/tmp/ord_phone.png')
    g=pg.locator('.nav-ord-on .nav-grip').nth(0); b=await g.bounding_box(); r2=await pg.locator('#main table.acct-tbl tr[data-href^="#account/"]').nth(2).bounding_box()
    x,y0,y1=b['x']+b['width']/2,b['y']+b['height']/2,r2['y']+r2['height']*0.75
    await cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':x,'y':y0}]})
    for i in range(1,11): await cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':x,'y':y0+(y1-y0)*i/10}]}); await pg.wait_for_timeout(20)
    await cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]}); await pg.wait_for_timeout(1000)
    print('phone after sliding the first one down:', await names())
    await pg.locator('.nav-ord-b').tap()
    await br.close()
asyncio.run(main())
